- server/controllers/LibraryController.js
- server/utils/index.js
- server/utils/parseOpfMetadata.js
When there is html in the description on a opf file it will strip it rather than not returning. It also gets series and volume number from the opf.
> Get more data from opf

- package.json
- server/ApiController.js
- server/utils/resizeImage.js
I've been playing around with the api and I thought it would be useful to be able to serve cover images at whatever size the client might want. This should accomplish that.
> Added an endpoint to serve different cover sizes

- server/providers/Audible.js
If the audible match contains special characters like german ä ö ü , the response is a bad request (400).
Example: "Wenn du mir gehörst"
https://www.audible.com/pd/Wenn-du-mir-gehoerst-Audiobook/B09MSG8PJ5
> Fix audible match if title or author has special characters

- client/components/cards/AudiobookSearchCard.vue
- server/objects/Book.js
Search now also searches books using isbn. ISBN match has to be exact to prevent isbn matches to flood results. 
I was thinking about two other approaches:
1. Only 10 and 13 character searches to be isbn searches since those are isbn lengths. This would limit using isbn field with other type of identify codes. I for one have some podcasts and other stuff that won't have isbn, but have guid instead.
2. Start searching isbn when search string is longer than 4,  because book name might have year in it. This might be good solution since not many books have more than 4 consecutive numbers so there would be no other results anyway. I don't know if there is use case for searching partial isbn. This would also require changes to client side search results list so you could see what part of isbn …
> Added isbn search

- package.json
- server/utils/prober.js
Swiched fluent-ffmpeg to node-ffprobe. Fluent's ffprobe implementation can't handle multiline tag data due to it's parsing process. There is open issue (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/457) about problem and even PR(https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/pull/476), but both are over 5 years old so I wouldn't hold my breath for that. 
node-ffprobe supports getting probe data using json format which keeps line changes. Not sure if this is best library for this but it won't have any dependencies and it does the job.
Tested with two mp3 files. One has metadata and one doesn't and it seemed to get same metadata as the old implementation. I advice you to do some testing if there is something that I didn't notice.
> Fixes reading multiline data from file tags

- client/components/controls/GlobalSearch.vue
Clicking on the series in the search result box now goes straight to the series instead of to the series library view.
> Fix: Series link from search goes straight to series

- build/debian/DEBIAN/preinst
- index.js
- prod.js
- server/Server.js
My local network runs mostly on ipv6, so I would like to be able to adjust the listening host (to "::" for me) to enable the server to listen on both ipv4 and v6.  This also allows people to limit the server to listen on specific IPs if needed.
> Allowed the configuration of a "HOST" parameter to enable ipv6 support.

- .gitignore
- client/package-lock.json
- index.js
- prod.js
Currently, all `TOKEN_SECRET`s are the same for all users. This is extremely insecure because everyone can decrypt secrets or connect to the DB.
Now users can provide their own `TOKEN_SECRET` to increase security.
Because the secret is also the DB password changing it requires backing up the previous instance, recreating it and then applying the backup
> Only fall back to the default secret when no env var is provided

- server/providers/Audible.js
When doing a scrape of my library, I noticed the following exception in the logs.
```
[2022-04-16T17:33:21.380Z] DEBUG: [Audible] ASIN url: https://api.audible.com/1.0/catalog/products/GOLDEN%20RENDEZVOUS?response_groups=rating%2Cseries%2Ccontributors%2Cproduct_desc%2Cmedia%2Cproduct_extended_attrs&image_sizes=500%2C1024%2C2000
(node:25) UnhandledPromiseRejectionWarning: TypeError: string-strip-html/stripHtml(): [THROW_ID_01] Input must be string! Currently it's: undefined, equal to:
undefined
at stripHtml (/node_modules/string-strip-html/dist/string-strip-html.cjs.js:228:11)
at Audible.cleanResult (/server/providers/Audible.js:20:26)
at /server/providers/Audible.js:64:65
at Array.map (<anonymous>)
at Audible.search (/server/providers/Audible.js:64:48)
at runMicrotasks (<anonymous>)
at …
```
> Update Audible scraper to be more strict about what it considers an ASIN and a valid ASIN query response

- client/components/app/LazyBookshelf.vue
- client/components/controls/FilterSelect.vue
This PR updates a couple bits of UI to include the filter *name* as well as the filter value.
The old UI only showed the selected filter "value" in the filter dropdown, and in the "no items found" message.
The new UI shows both the filter name *and* the filter value, making it clearer what's being filtered
> Include the type of filter being applied in the UI

- client/components/controls/FilterSelect.vue
- server/utils/libraryHelpers.js
When organizing a large audiobook library, it can be useful to filter by books that are *missing* specific fields, to make it easier to know which books need further edits.
This PR adds new filters to the UI that enable this functionality.
| Top Level  | Sub Menu|
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/91645868/163922233-a03d25ec-2fe5-41ab-b10a-e22ecd5590b0.png)  | ![image](https://user-images.githubusercontent.com/91645868/163922275-d21d0ab9-33d9-41e2-9ed8-06f60c50479b.png)  |
I kinda just followed the examples I could already see from the UI and backend filtering code, but I'm more familiar with React than with Vue, so let me know if I need to rework anything :)
> Proposal: Add a filter for media that is missing specific fields

- client/components/controls/GlobalSearch.vue
Same fix as app, global search feature returned an undefined id for books and podcasts so sent user back to home when trying to click on something they searched. Same error and fix as the mobile app.
> Fix libraryItem ID reference in global search

- server/scanner/Scanner.js
I noticed the following exception from the scanner:
```
/server/njodb/index.js:103
throw error;
^
TypeError: Cannot read properties of undefined (reading 'startsWith')
at /server/scanner/Scanner.js:521:98
at Array.find (<anonymous>)
at Scanner.scanFolderUpdates (/server/scanner/Scanner.js:521:51)
at Scanner.scanFilesChanged (/server/scanner/Scanner.js:501:42)
at Server.filesChanged (/server/Server.js:266:24)
at FolderWatcher.emit (node:events:526:28)
at Timeout._onTimeout (/server/Watcher.js:194:12)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
```
This was after fixing the folder nesting of some audiobook files:
```
/audiobooks/B A Paris/                            
/audiobooks/B A Paris/Behind Closed Doors.mp3     
/audiobooks/B A …
```
> Update folder update logic to use new media path name

- server/scanner/Scanner.js
All the audiobook media providers seem to provide a `description` field, so we're just failing to apply it to the media item after it is looked up. This PR updates the list of updated properties to include `description`, so now doing a Quick Match or matching an entire library should also update media item descriptions if available.
> Set description when quick matching media

- client/pages/config/backups.vue
- server/managers/BackupManager.js
- server/objects/settings/ServerSettings.js
On sufficiently large libraries, backups can start to fail because they hit the hardcoded 1GB backup limit. This PR makes that limit configurable so that users with large libraries can set a larger limit.
Screenshot of new UI:
> Make maximum backup size configurable

- server/utils/scandir.js
When a library has a root folder containing no media items, a warning is logged when scanning.
```
[2022-04-25T22:28:15.859Z] ERROR: Root path has no media folders 0
```
However, that `0` isn't really helpful since we already know the root path is empty.
This PR updates the log message to instead log the folder path:
```
[2022-04-25T22:26:52.842Z] ERROR: Root path has no media folders: C:/code/audiobookshelf/audiobooks2
```
> Log full path when warning about empty root

- client/components/modals/libraries/EditModal.vue
- client/components/modals/libraries/LibrarySettings.vue
- server/objects/settings/LibrarySettings.js
- server/scanner/Scanner.js
For very large media libraries, the library matcher can spend an inordinate amount of time re-querying info for books that have already been matched. This makes book matching take forever, and I'm also concerned that it could eventually lead to getting your IP blocked for abuse for repeatedly scanning thousands of books at a time.
This PR adds two new switches to the library settings, to skip matching books that already have an ISBN or ASIN set. This gives users more control over whether to skip matching books that have potentially already been matched.
When the matcher can skip books that already have an ISBN/ASIN, it will log a messages will look like this:
```
[2022-04-27T00:33:28.293Z] DEBUG: [Scanner] matchLibraryItems: Skipping "Breakdown" because it already has an ASIN (1 of 6) …
```
> Add options to skip matching media items if they already have an ASIN/ISBN

- client/components/app/Appbar.vue
Adds tooltips to edit, delete, and deselect all buttons when multiple audiobooks are selected.
> Added tooltips missing from Appbar buttons

- server/managers/BackupManager.js
I've been noticing that recent backups weren't being displayed in the UI, and was finally able to figure out why. When Audiobookshelf is finding backups, it has to load the archive to get info about the backup version etc. If the archive is corrupted, the following error is thrown and Audiobookshelf stops loading any remaining backups.
```
[ERROR: [BackupManager] Failed to load backups Error: Bad archive
at FsRead.readUntilFoundCallback [as callback] (/node_modules/node-stream-zip/node_stream_zip.js:198:39)
at FsRead.readCallback (/node_modules/node-stream-zip/node_stream_zip.js:996:25)
at FSReqCallback.wrapper [as oncomplete] (node:fs:660:5)
```
To fix that issue, this PR adds an inner try/catch to handle that specific `Bad archive` error, log a message, and continue loading any other …
> Handle corrupted backups gracefully and continue loading other backups

- client/components/controls/EpisodeSortSelect.vue
- client/components/modals/podcast/EditEpisode.vue
- client/components/tables/podcast/EpisodeTableRow.vue
- server/objects/entities/PodcastEpisode.js
- server/utils/podcastUtils.js
Podcasts such as [Command Line Heroes](https://podcasts.apple.com/us/podcast/command-line-heroes/id1319947289) have multiple seasons in which each has it's own "Episode 1, ••• Episode n". This seeks to add support for this class of podcast series.
> Add support for seasonal podcasts

- server/utils/scandir.js
Following the refactor of getBookDataFromDir, if subtitle parsing is turned off, then the title is not imported at all. This fixes it and also resolves your confusion about variable scope.
> URGENT: Fix to serious bug

- server/managers/BackupManager.js
A few weeks ago I added some logic to handle one kind of backup file corruption when listing backups in #555. Today when looking at my backups, I found that there's another type of error that should also be handled. Namely, when a backup file is unexpectedly truncated.
> Gracefully handle unexpected end of file when listing backup files

- .github/workflows/docker-build.yml
- Dockerfile
- readme.md
* Clean up Dockerfile 
* Add health check to Dockerfile [662](https://github.com/advplyr/audiobookshelf/issues/662)
* Update gh action versions
* Update manual trigger to include input [661](https://github.com/advplyr/audiobookshelf/issues/661)
> feat: Updates to docker file and gh action

- server/managers/AudioMetadataManager.js
This commit resolves issue #676 . The embed metadata tool was missing the flag that tells ffmpeg to not only update the "top" metadata, but also the chapter metadata.
I tested this manually by adding a file to my library and testing before and after this change, and validating the change through ffprobe.
> Support embedding updated chapter metadata (issue #676)

- server/managers/AbMergeManager.js
This commit fixes an issue where cover art was not being generated properly when creating an M4B audiobook from MP3 files. Thanks to @advplyr for pointing out what the actual fix was for this
More context can be found in discord:
https://discord.com/channels/942908292873723984/981321213882282035/982777444631195681
These are available in the discord conversation as well, but here are what the covers look like now, in various forms:
> Fix cover art not being generated for M4B export

- server/Server.js
- server/managers/AbMergeManager.js
- server/managers/CacheManager.js
This PR resolves #698.
mkdir was being used instead of [ensureDirs, or mkdirs or mkdirp](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir.md). AbMergeManager doesn't precreate the Downloads folder structure it needes -- updating it to use ensureDirs handles creating the entire path needed when a merge attempt gets kicked off.
I also did a driveby and updated mkdir for CacheManager to also leverage ensureDirs. CacheManager was a bit safer already, but if the first mkdir had failed for any reason, the resulting ones would have failed as well, resulting in a server crash at startup. While changing these to ensureDir doesn't necessarily guarantee whatever might cause the first creation to fail won't happen again on these subsequent attempts, it will at least mean that …
> Update some instances of mkdir to ensureDir (#698)

- server/utils/prober.js
FFmpeg only supports a very limited number of tags for m4b files (see https://wiki.multimedia.cx/index.php?title=FFmpeg_Metadata). `series` and `series-part` are not possible to use. To work around that, `show` and `episode_id` are added as second option.
> Use `show` and `episode_id` tags for audiobook series

- server/utils/prober.js
Looks like #697 missed a reference update that caused scanning libraries to fail. This fixes that. Also confirmed there are no other references to `TryGrabTag` left
> Fix library scanning failing

- .gitignore
- client/pages/audiobook/_id/chapters.vue
- client/pages/config/index.vue
- server/controllers/PodcastController.js
- server/objects/mediaTypes/Book.js
- server/objects/metadata/AudioMetaTags.js
- server/objects/metadata/BookMetadata.js
- server/objects/settings/ServerSettings.js
- server/scanner/LibraryScan.js
- server/scanner/MediaFileScanner.js
- server/scanner/ScanOptions.js
- server/scanner/Scanner.js
- server/utils/parsers/parseOverdriveMediaMarkers.js
- server/utils/prober.js
Overdrive MP3s come in multiple parts when downloaded from Overdrive with each part containing a certain number of chapters. Each part also includes a special metadata tag, called `OverDrive MediaMarkers` that describes the timestamps for those chapters (relative to the part) in an XML format.
This PR adds support to ABS to natively parse the `OverDrive MediaMarkers` metadata, and offer the option to use it to populate the chapter metadata in ABS during scanning. Users can toggle this functionality as a server setting from the server settings UI. 
Once enabled, it behaves similarly to other metadata scanning:
- For existing books, it requires a force re-scan (either individual, or at the library level) to apply
- For new books, it will take place automatically upon a regular scan, a force …
> Add support for leveraging chapter data directly from Overdrive mp3s during scanning

- client/components/ui/MultiSelect.vue
I noticed in #730 that the pills were touching when there was an overflow. This changes that so there is space between them on the y.
Before:
After:
> Update details "pills" so they don't overlap when they flow to new lines

- client/components/ui/MultiSelect.vue
In the unlikely chance that someone has quite a long entry for one of the fields that leverage pills, the current behavior is to have it run off out of the modal. This commit updates that to support breaking it to multiple lines.
Before (if long enough, it will just keep going off the modal/screen):
After:
After (with #732 ):
> Update pills so that they handle multi-line properly

- package.json
I wanted to spin up a local instance of ABS with the latest changes, so I added a few local build options for docker. `--load .` will automatically load the image in to your local docker image repo after building
```
✔≻ npm run docker-amd64-local
> audiobookshelf@2.0.21 docker-amd64-local
> docker buildx build --platform linux/amd64 --load .  -t advplyr/audiobookshelf-amd64-local
[+] Building 2.0s (16/16) FINISHED                                                                                                                                                           
=> [internal] load .dockerignore                                                                                                                                                       0.0s
=> => transferring context: 189B …
```
> Add npm commands to build local docker containers

- server/finders/BookFinder.js
I got the idea from @sxb1n9 and his PR here https://github.com/advplyr/audiobookshelf/pull/680
My audiobooks with (unabridged) in the title never get picked up by the search function. This will fix that as well as in cases like "Ender's Game (Ender's Saga)"
Pro: 
- This won't run unless no books were found the first time around
- This uses existing functions `cleanTitleForCompares` and `cleanAuthorForCompares`  
Con:
- Twice the API calls if no books are found the first time around  
https://user-images.githubusercontent.com/39509289/174258568-614ff5cb-16ec-4cb4-8960-c31e91184b59.mp4
> Update BookFinder.js: Retry Search with Clean Title and Author if No Books Found

- client/components/app/Appbar.vue
- client/components/controls/GlobalSearch.vue
- client/components/ui/LibrariesDropdown.vue
This commit aims to fix #715
This is my first time doing responsive CSS. I'll be refining this -- just wanted to get an initial draft up. I'm trying to follow tailwind's best practices for mobile [laid out here](https://tailwindcss.com/docs/responsive-design#mobile-first) of targeting mobile by default, and then using breakpoints for everything else.
A few things I'm trying to achieve:
- Keep the ABS logo as a valid sized touch target
- Ensure that the libraries panel leverages an adequate amount of space, regardless of the libraries button size
- Ensure that search results leverages an adequate amount of space, regardless of the search bar input size 
GIF
:
> Show search bar on mobile responsive views (fix #715)

- client/components/modals/item/tabs/Match.vue
This commit fixes #719 adds support for multiple narrators when matching. We were accidentally missing a split in the same way we handle it for genres and tags.
Screenshot of this fix with the ASIN data linked in #719:
> Properly support multiple narrators when Matching (#719)

- client/components/modals/authors/EditModal.vue
- server/controllers/AuthorController.js
- server/finders/AuthorFinder.js
At the moment, there is no easy way to add a photo for an author, if one isn't found during a (quick)match
This PR adds a new text field 'Photo URL' on the author edit modal, shown only if there is no existing image for an author. When submitted the image is saved from the URL provided, using the existing AuthorFinder.saveAuthorImage() method.
> Fetch author photo from external URL

- client/components/app/StreamContainer.vue
- client/components/controls/PlaybackSpeedControl.vue
- client/components/controls/VolumeControl.vue
- client/components/player/PlayerPlaybackControls.vue
- client/components/player/PlayerTrackBar.vue
- client/components/player/PlayerUi.vue
- client/components/ui/Tooltip.vue
- client/tailwind.config.js
This commit adds support for the request in #741. It borrows some of the logic from audiobookshelf-app and it's chapter track functionality. This PR specifically adds the toggle to swap the existing UI; a future PR can look to add the dual-track-bar functionality that abs-app has currently.
Example GIF (ignore the fact that towards the end of the gif, the chapter/book times are wrong... the chapter data on this book is incorrect :roll_eyes: ):
> Add toggle for switching between Chapter and Book Duration in player (issue #741)

- client/components/app/BookShelfRow.vue
I noticed in the non-alternative view that "Continue Listening" was wrapping. This PR updates the placards to be large enough to not force a wrap. I also moved the placards down 1px so they align better with the shelf
Before:
After:
> Fix placard sizes so "Continue Listening" fits

- client/pages/config/index.vue
Noticed this button didn't have proper right padding.
Before:
After:
> Fix padding on "Remove All Library Items" button

- client/components/app/ConfigSideNav.vue
- client/pages/config/log.vue
I noticed the Log page had a different UI then most of the other settings UI pages, and had some weird graphical weirdness with the div wrapping it. This PR brings it inline with the others. As well, I updated the h1+left nav to be "Logs" which is more inline with the other items. Lastly, I increased the size of the content on the page to 800px -- this should be an appropriate size for 1080p which is the most common resolution (as seen in the screenshots below of 1080p)
Before:
After:
> Update Log page to have a matching "settings UI"

- client/layouts/default.vue
This PR moves a bunch of the toasts that can appear to be from the bottom middle of the screen, blocking the player (#702), to the top right, where the other toasts show up. The connection error / server disconnected toast did not get changed, as I think it makes sense for something like that to impede functionality.
Before:
After:
>  Move matching toasts to top right (Issue #702)

- client/components/app/ConfigSideNav.vue
- client/pages/config/sessions.vue
Similar to #748 , the UI on this page was slightly different from the other ones. In both of these, I think there is room for improvement in a future PR on the headers (when there is a picker with a label, it _feels_ like there is a lot of whitespace because we align it to the right. We also had enough room to unify on the left nav + page h1, so I updated that.
Future Work: We should probably extract out the "Header" on these pages to it's own component, and standardize the controls for search + input select
Before:
After:
> Update Sessions page to have a matching "settings UI"

- client/components/tables/UsersTable.vue
Continuing in the list of PRs to align all of these pages together, this one updates the Users table to have a matching visual UI to the Sessions table. This is just to make it match -- as mentioned in the sessions table PR, there is some good future PR work available here to extract all of this out so we aren't duplicating it across tables across pages.
Before:
After:
> Update UsersTable styling to match other tables

- client/pages/config/index.vue
This PR updates the settings page UI. This biggest changes here are a more distinct visual hierarchy of the content, as well as moving the content to 2 columns when above the small break-point to reduce scrolling. With the groupings introduced in 8ab0f164, I also streamlined the text to be less redundant, which helps with the cognitive load of looking at a bunch of text at once
**Before (desktop):**
**After (desktop):**
**Before (mobile-web):**
**After (mobile-web):**
> Update Settings page UI

- client/pages/config/library-stats.vue
- client/pages/config/stats.vue
This PR updates both the Library Stats and Your Stats UIs. The 2 main changes are the content div styling, and ensuring both are using h1 headers for the titles
Before:
After:
> Update Library Stats and Your Stats UIs to match other Settings UIs

- client/components/modals/ChaptersModal.vue
This PR resolves #767 by adding the chapter duration alongside the chapter start timestamp. I went with showing them both at once rather than a toggle in the settings to change between these, as having it be a toggle could lead to more confusion (forgetting you had it set and not knowing why the times were not linear, or sharing with multiple users who have different preferences). If we end up adding the concept of user-scoped settings in the future, we should look at moving this over to there. 
Before
After
> Show chapter duration in the "now playing" chapter modal (Issue #767)

- client/components/player/PlayerTrackBar.vue
Fixes an issue where seeking by clicking the track bar acts as if the whole book's duration is being seeked.
> fix: use chapter duration when seeking on track bar

- server/managers/CacheManager.js
Remove cachePathsExist property to ensure missing cache directories are recreated when EnsureCachePaths() called.
> Remove cachePathExists property (Issue #800)

- server/controllers/MeController.js
This PR fixes an issue with getMediaProgress always returning an actual value.
Before:
`Not Found`
After:
```
{
"id": "li_7ldrc1h3c2vn6fmf8v",
"libraryItemId": "li_7ldrc1h3c2vn6fmf8v",
"episodeId": null,
"duration": 198346.729125,
"progress": 0.1297424974615144,
"currentTime": 25734,
"isFinished": false,
"lastUpdate": 1656618353652,
"startedAt": 1656516106482,
"finishedAt": null
}
```
> fix getMediaProgress always returning 404

- docker-compose.yml
Added `restart: unless-stopped`
Adjust volumes - probably shouldn't be scattering the volumes around the root dir? Could also do this to put them in the home dir instead of relative to the .yml file location:
```
- ~/abs/audiobooks:/audiobooks
- ~/abs/metadata:/metadata
- ~/abs/config:/config
```
https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
> Add restart and fix volumes

- client/components/modals/podcast/EpisodeFeed.vue
- package-lock.json
Clears the selectedEpisodes once the download is started.  Fixes #931.  
Also, clicking on the checkbox for existing downloads still added that item to the list.  Moved onClick to checkbox instead of container div to prevent this.
> Clear selectedEpisodes on download.  

- client/components/controls/VolumeControl.vue
I've noticed ABS does not persist the volume in local storage like many other players so refreshing the page sets the volume back to 100%. This commit stores and retrieves the volume from the browser's local storage.
> Persist Volume in Local Storage

- client/components/app/Appbar.vue
- client/components/modals/BatchQuickMatchModel.vue
- client/layouts/default.vue
- client/store/globals.js
- server/controllers/LibraryItemController.js
- server/routers/ApiRouter.js
- server/scanner/Scanner.js
Adds a feature to allow the user to batch Quick Match the selected audiobooks.
A button is added to the Appbar when one or more audiobooks are selected using the multi-select option (left most button on the below image).
Once clicked, a dialog is shown allowing the user to select the metadata provider and to select whether exiting covers or metadata should be overwritten.
When "Continue" is selected, a quick match is run against each selected audiobook, updating metadata and covers as required.
> Multi select quick match

- server/controllers/LibraryController.js
- server/objects/metadata/BookMetadata.js
- server/objects/metadata/PodcastMetadata.js
- server/objects/metadata/VideoMetadata.js
- server/utils/index.js
- server/utils/libraryHelpers.js
I noticed that when sorting with ignore prefix on, items were not actually sorted correctly. For example, imagine having three items:
"The A"
"The A B"
"The A C"
This sorted to
"A B, The"
"A C, The"
"A, The"
This happens because the ", The" is part of the sort operation. I've modified the code so that is no longer the case. I chose to leave the Vue side of things alone, so the true sort value is only available to the server.
> Makes it so the when sorting and ignoring prefixes, prefixes are actually ignored

- client/components/app/BookShelfToolbar.vue
- client/components/app/LazyBookshelf.vue
- client/components/cards/LazyBookCard.vue
- client/components/controls/LibrarySortSelect.vue
- client/store/user.js
- server/controllers/LibraryController.js
- server/utils/libraryHelpers.js
I noticed that there was an issue with the "Collapse Series" option in the Library view that happens when a book is in two series at the same time. For example, in the Pern series of books, the first three books are part of a trilogy (series A) and part of the overall Pern universe (series B). If I label them as such, one of those series will disappear from the view, even though both should be shown. They still show up in the series list, so this is just a display issue.
While fixing this problem, I also noticed that code for sorting books attached to multiple series wouldn't work correctly as sorting happened before collapsing. I've reworked the sorting to have collapsing occur first, then sorting after that. I also fixed a couple of other small issues with sorting:
1. When series are …
> Patching handling of titles with multiple series

- server/controllers/LibraryController.js
I realized I made a mistake and broke range collapsing for series tags. This fixes that.
> Fixing range generation in series labels

- client/pages/config/users/_id/index.vue
Fixes the bug reported [here](https://github.com/advplyr/audiobookshelf/issues/1142) where listening sessions weren't being reported properly on the user details page.
Rather than adding a new field to `listening-stats` as discussed in the issue, I opted to utilize the `total` field already given by `listening-sessions`, necessitating a very minor refactor of how we get the `latestSession`
> Fix listening sessions count bug

- client/components/ui/Tooltip.vue
When using accessibility tools like screen magnifiers, dynamic screen content can be quite problematic. In particular content, which only appears if you interact with elements somewhere else on the screen. That is the case, for example, with the current implementation of tooltips used by audiobookshelf.
This patch provides a slight adjustment, keeping the tooltips open if you hover over them. This allows users to have better access to the content.
For those unfamiliar with e.g. screen magnification tools, here is a short example:
https://user-images.githubusercontent.com/1008395/202920990-3df731c9-29a6-442d-b845-61364d45c20b.mp4
You couldn't have read the right half of the tooltip if it would still disappear immediately.
> Make Tooltips Accessible

- server/managers/RssFeedManager.js
This patch drops the log level for logging requests to non-existing feeds from error to debug. The reasoning behind this is that this is a client error and a client error is returned and can be handled by the client.
Otherwise anyone can easily spam the logs with error messages by just requesting non-existing feeds.
> No feed log level

- client/components/modals/authors/EditModal.vue
If you are on the home page and open the edit author modal, you can automatically update all data by clicking “Quick Match” or you can remove a set image by clicking 🗑.
Both options will update the actual data, but not the data in the open modal. This means that, for example, a picture is still shown in the modal after deleting it. That's confusing.
This patch fixes the bug and makes sure the modal is updated if the data is updated.
> Update Author Modal on Changes

- server/controllers/MeController.js
This patch updates the batch progress update endpoint to respond with a `400 Bad Request` instead of a `500 Internal Server Error` if a user sends an invalid request with no body. This is a user error after all.
```
❯ curl -i -X PATCH \
'http://127.0.0.1:3333/api/me/progress/batch/update' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5Q_MoRptP0oI' \
-H 'Content-Type: application/json'
HTTP/1.1 400 Bad Request
…
Missing request payload
```
> Respond with bad request to unvalid request data

- server/objects/user/MediaProgress.js
This patch is a minor extension to the update progress and batch update progress API and allows you to specify `finishedAt` and `startedAt` when updating a progress.
If not specified, both values are still automatically set to the current time. If just `finishedAt` is specified, `startedAt` is set to the same value.
Example API request:
```
❯ curl -i -X PATCH \
'http://127.0.0.1:3333/api/me/progress/li_ywupqxw5d22adcadpa' \
-H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJyb290IiwidXNlcm5hbWUiOiJyb290IiwiaWF0IjoxNjY4OTYxNjAxfQ._NbilCoFy_hfoqy7uvbV4E_0X6qgLYapQ_MoRptP0oI' \
-H 'Content-Type: application/json' \
--data-raw '{"isFinished":true, "finishedAt": 1668556852000, "startedAt": 1668056852000}'
```
> Allow specifying start and end of progress via API

- server/objects/user/MediaProgress.js
If no progress had been set before, setting `startedAt` did not work and it would always been set to `finishedAt` or `Date.now()`. Settings this if any progress had already been recorded did work.
This fixes the problem so that setting `startedAt` it properly works in both cases.
> Fix startedAt in progress API

- client/pages/config/notifications.vue
The settings pages were all unified in #755 #757 #758 and #759. This PR unifies the new notifications settings page as well to be consistent with the others
**Before**
**After**
> Update notification settings UI to match other pages

- server/providers/GoogleBooks.js
The API for Google Books will return HTTP image URLs when matiching any books using it as a search provider. In a secure environment, this causes browser warnings.
All Google image links support HTTPS and we can safely switch to HTTOS to avoid these warnings.
> Use HTTPS for Google Books Images

- server/scanner/Scanner.js
If the scanner detects new files with a path containing part of the name of an already existing library item, the new item will incorrectly be detected as being a parent directory of the already existing item and the import will be aborted.
You can follow these steps to reproduce the issue:
```
❯ mkdir audiobooks/author/
❯ mv title\ 10 audiobooks/author
[2022-12-18 22:14:12] DEBUG: [Watcher] File Added /home/lars/dev/audiobookshelf/audiobooks/author/title 10/dictaphone.mp3
[2022-12-18 22:14:16] DEBUG: [DB] Library Items inserted 1
❯ mv title\ 1 audiobooks/author
[2022-12-18 22:15:03] DEBUG: [Watcher] File Added /home/lars/dev/audiobookshelf/audiobooks/author/title 1/dictaphone.mp3
[2022-12-18 22:15:07]  WARN: [Scanner] Files were modified in a parent directory of a library item "title 10" …
```
> Fix Sub-path Detection

- build/debian/lib/systemd/system/audiobookshelf.service
This patch removes `PermissionsStartOnly=true` from the systemd unit file used for packaging. This shouldn't be necessary for any commands run by the unit.
Note that while I'm pretty sure that this is not necessary, I did not test this.
We should do that before merging this.
> No PermissionsStartOnly=true

- index.js
Assigning something to `process.env.profile`, Node stringifies the value. This means that assigning `undefined` to an environment variable in Node will result in it holding the string `undefined`.
This means, for example, that `module.exports.FFPROBE_PATH || 'ffprobe'` in `server/libs/nodeFfprobe/index.js` will actually result in the string `undefined`.
This patch fixes several such assignments in the `index.js`, potentially causing problems in the development mode.
> Fix undefined string assignment

- client/components/app/Appbar.vue
This patch adds the missing alt attribute to the image linking the home page of audiobookshelf. This allows screen readers to explain to users where this link leads to.
> Text description of home link

- client/components/app/Appbar.vue
- client/components/ui/LibrariesDropdown.vue
This patch highlights items in the app bar if a user uses the keyboard to navigate in audiobookshelf. This ensures that users actually know which item they have selected.
This also modifies the text for the library selector, so that users which are using a screen reader understand that it is a selector for libraries and not only a button related to the current library.
> Highlight items when navigating via keyboard

- client/components/ui/LibrariesDropdown.vue
This patch fixes the keyboard navigation in the library selection of the main app bar. Without this patch, no options are selectable via keyboard and selecting an option and hitting return has no effect.
> Fix keyboard navigation in library selection

- client/components/app/SettingsContent.vue
- client/components/modals/AccountModal.vue
- client/components/ui/Dropdown.vue
- client/components/ui/TextInput.vue
- client/components/ui/TextInputWithLabel.vue
- client/components/ui/ToggleSwitch.vue
This patch should fix most of the problems for users trying to access the user settings via screen reader. It makes sure user interface elements can be reached via keyboard and provides proper labels, roles and values so you not only can interact with elements but also know what you are actually changing.
While not focused on other views, this should also already fix a number of accessibility issues with other settings pages.
> Make User Settings Accessible via Screen Reader

- client/components/tables/UsersTable.vue
- client/strings/de.json
- client/strings/en-us.json
This patch makes sure that the option in the user settings are accessible via keyboard navigation and that the labels, if users use a screen reader, actually make sense.
This patch introduces new strings which need to be translated. Although I did already provide a German translation.
As a minor visual details, this patch also aligns the delete and edit icons:
> Fix keyboard navigation in user settings

- client/components/ui/Dropdown.vue
- client/pages/config/index.vue
This patch fixes some accessibility problems on the main settings page. Most notably, it makes sure that the different options have labels which are picked up by screen readers.
As a more generic addition, this also makes sure that the dropdown component will always have a proper label constructed, explaining what the dropdown is for and what its current value is.
> Accessibility Improvements for Main Settings

- client/components/app/ConfigSideNav.vue
- client/pages/config.vue
- client/store/globals.js
This patch fixes several problems of the settings menu related to display on mobile devices or small(ish) windows:
- The `isMobileLandscape` is now calculated correctly. Previously, this was set to `true` if a device was in portrait mode.
- Showing the button to collapse the settings menu and making the menu collapsible now use the same mechanism. Previously, it could happen that the menu was opened and not fixed, but no button to close it again was shown.
- The icons fore opening and closing the settings menu are now both arrows, indicating that their functionality is reversed.
- The button to open the menu now always has the string “Settings”, instead of using the name of the current page. The current page hader is listed below that anyway and this is the action component to open the …
> Fix Hidden Settings Menu

- server/Logger.js
- server/Server.js
The Audiobookshelf logs sometimes contain information about the source of the log statement, but sometimes they don't This really depends on developers adding these information to the log messages.
But even then, the information is usually just a hint about the module logging this, like `[Db]` or [Watcher]`, and finding the exact line can be hard.
This patch automatically adds the source of the log statement to the logs. This means if someone calls `Logger.info(…)` in line `22` of `foo.js`, the log statement will contain this file and line:
```
[2023-01-05 19:04:12[ (LogManager.js:85:18) DEBUG: Daily Log file found 2023-01-05.txt
[2023-01-05 19:04:12] (LogManager.js:59:12)  INFO: [LogManager] Init current daily log filename: 2023-01-05.txt
```
This should make it much easier to identify …
> Add Source to Logging

- client/components/app/SettingsContent.vue
- client/components/tables/UsersTable.vue
- client/components/ui/ToggleSwitch.vue
This patch fixes the problem that toggling one of the options in the user account dialog will automatically submit the form.
The problem got introduced as a combination of the recent accessibility fixes where some elements got turned into HTML button elements to make them keyboard accessible. Doing that, I did not realize that [the default type of a button is `submit`](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#attr-button-type). This causes no problems at most places, but will cause problem within a form (e.g. the user account settings) where toggling an option is now identical to clicking submit.
This patch fixes the issue by setting the `type` attribute to `button`. Not only for the toggle switch, but also for a few other elements which have been recently …
> Toggle switch shouldn't submit form

- server/utils/libraryHelpers.js
This patch changes the books displayed in “Continue Series”, avoiding books if another book from the series is played back right now. This prevents Audiobookshelf suggesting books to which users will not listen to because they are still listening to the last one.
Once a book is finished, the next book in the series will pop still be suggested to the user.
This fixes  #1382
> Show next book only if previous book is finished

- server/utils/libraryHelpers.js
Sometimes, a book belongs to more than one series. If you listen to and finish such a book, Audiobookshelf will list the next book in “Continue Series” twice, right next to each other. That is not helpful.
This patch fixes the problem by not adding books to the list if they are already in the list.
> Don't list book twice in continue series

- index.js
- prod.js
- server/Server.js
- server/utils/filePerms.js
This patch slightly changes the behavior of the `AUDIOBOOKSHELF_UID` and `AUDIOBOOKSHELF_GID` options. Instead of defining a default user and group, trying to modify files and silently failing if the filesystem mode cannot be changed, this patch will just skip the entire process in the first place.
If these options are defined, Audiobookshelf should behave exactly as before. If they are not defined, Audiobookshelf will now cause fewer file modifications (or less failures when trying to modify files).
If this patch gets applied, it should probably be highlighted in the release notes. This usually shouldn't cause problems for migrations since the Docker guides explicitly configure the options and the package installations do not seem to use this at all, but there is still a change that it …
> Skip AUDIOBOOKSHELF_UID/GID if undefined

- server/Server.js
As DieselTech#6997 pointed out in Matrix, it is a good idea to reduce fingerprinting by removing the `X-Powered-By` response header as pointed out by the Express security best practices:
See http://expressjs.com/en/advanced/best-practice-security.html#reduce-fingerprinting
> Reduce Fingerprinting

- server/utils/htmlSanitizer.js
Fixes #1418. HTTP links in show notes didn't work because `sanitize` in `server/utils/htmlSanitizer.js` removes them, as only `https` was set in `allowedSchemes`. This commit adds `http`.
`htmlSanitizer/sanitize` is only used for podcast and episode descriptions (in `server/utils/podcastUtils.js` and `server/providers/iTunes.js`) , so I don't think there's any reason to disallow HTTP.
> Fix HTTP links not working in podcast show notes.

- client/components/ui/InputDropdown.vue
This PR resolves #1410. We were using a `<p>` instead of a `<label>` on `InputDropdown`. Label makes more sense here, as it's inline with the way you would typically add a label to an input component.
**Before**
**After**
> Align "Series Name" and "Sequence" inputs on Series Editor modal

- server/Server.js
- server/controllers/LibraryItemController.js
- server/managers/CacheManager.js
- server/routers/StaticRouter.js
This patch implements [X-Accel](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) redirect headers as an optional way for offloading static file delivery from Express to Nginx, which is far better optimized for static file delivery.
This provides a really easy to configure way for getting a huge performance boost over delivering all files through Audiobookshelf.
How it works
------------
The way this works is basically that Audiobookshelf gets an HTTP request for delivering a static file (let's say an audiobook). It will first check the user is authorized and then convert the API path to a local file path.
Now, instead of reading and delivering the file, Audiobookshelf will return just the HTTP header with an additional `X-Accel-Redirect` pointing to the file location …
> Implement X-Accel Redirect

- client/components/stats/DailyListeningChart.vue
- client/components/stats/Heatmap.vue
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/fr.json
- client/strings/hr.json
- client/strings/it.json
- client/strings/pl.json
- client/strings/zh-cn.json
I modified the page a bit to accept the translated strings for abbreviated Month and Days
I have not changed the non translated elapsed string in the Recent Session Pane because it is an output of lib date-fns formatDistance function and I need to dig a bit into it to see how to do local with date-fns
> Localized stats page

- server/objects/settings/ServerSettings.js
This patch updates the default value of the home page bookshelf view so that it is identical to the default library view. Having different styles by default seems odd. I picked the non-wooden view as default based on the recent discussion on Matrx/Discord that that one looks more modern.
> One Default Bookshelf View

- server/objects/mediaTypes/Book.js
- server/objects/mediaTypes/Podcast.js
- server/utils/abmetadataGenerator.js
Modified the reading / saving of metadata.abs to allow for the reading and writing of tags.  Used JSON functions to stringify the objects to handle escape characters automatically, then JSON.parse to get it back in.
Tried to make the read / write as error proof as possible so it would function with files that do not have the tags entity in the metadata file.
> Adding tags to metadata.abs

- server/libs/nodeFfprobe/index.js
- server/scanner/MediaFileScanner.js
When audiobookshelf scans a folder with a lot of files, it will take up a lot of memory, because audiobookshelf will start a ffprobe process for each media file at the same time. In order to reduce memory usage, it is necessary to limit the number of ffprobe processes started at the same time.
In addition, after the ffprobe process is executed, it does not exit immediately and becomes a zombie process. It is necessary to call kill() in the exit event to end the process.
Before:
After:
> Reduce memory usage when scanning large folders

- client/store/scanners.js
- server/finders/BookFinder.js
- server/providers/FantLab.js
I've added a new book match provider. [fantlab.ru](https://fantlab.ru/) is a huge site with tens of thousands of book descriptions in Russian and not only (Russian is still the main language).
This is my first js code, my main activity is a .net developer. So if there are simple errors in the implementation, then please do not kick hard. :)
> FantLab.ru BookFinder

- server/managers/NotificationManager.js
- server/utils/notifications.js
This adds the `libraryTags` variable to the `onPodcastEpisodeDownloaded` notification handler.
This helps in the usecase where multiple users have access only to limited tags.
In this case they can filter the sent out notifications only for the tags that they are interested in and are no longer pinged for every podcast downloaded.
Example:
> Add library tags variable to podcast notifications

- .github/workflows/integration-test.yml
This patch adds a minimal integration test building Audiobookshelf as a binary, running it and checking if the server is available on each push and pull request.
We can easily extend this with a Selenium or Playwright test later, but it should already alert us about problems in the build pipeline without the need for any developer to take a look at the new patches.
> Integration Test

- server/objects/PodcastEpisodeDownload.js
Thanks for all the great work on audiobookshelf! This is a small change to fix a error that I encountered: 
```
ERROR: [PodcastManager] Podcast Episode download failed TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
at new NodeError (node:internal/errors:387:5)
at new ClientRequest (node:_http_client:182:13)
at Object.request (node:https:357:10)
at RedirectableRequest._performRequest (/node_modules/follow-redirects/index.js:284:24)
at new RedirectableRequest (/node_modules/follow-redirects/index.js:66:8)
at Object.request (/node_modules/follow-redirects/index.js:523:14)
at dispatchHttpRequest (/node_modules/axios/lib/adapters/http.js:262:25)
at new Promise (<anonymous>)
at httpAdapter (/node_modules/axios/lib/adapters/http.js:49:10)
at dispatchRequest …
```
> Encode podcast url when downloading episode

- client/pages/config/library-stats.vue
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/fr.json
- client/strings/hr.json
- client/strings/it.json
- client/strings/pl.json
- client/strings/ru.json
- client/strings/zh-cn.json
- server/controllers/LibraryController.js
- server/utils/libraryHelpers.js
- Add a new stats item listing the top 10 largest podcasts/books
- Affects the podcast and book stats page
- Like the longest items stats that use the total duration for an item (summing all the duration of all media in a podcast/book), on the largest items, I am summing all the sizes of all media within a podcast.
> Add largest item stats

- client/components/modals/item/tabs/Schedule.vue
- client/components/widgets/CronExpressionBuilder.vue
Today if you set up a schedule for each podcast, you can see the configuration if you access each podcast individually.
But if you try to use the prev/next button to navigate between each podcast schedule, the configuration is not refreshed, and the modal freeze on the first podcast configuration.
This pull request fixes the configuration loading when you use the prev/next button to navigate on the schedule modal.
efore I access each podcast schedule configuration individually after I try to use the Prev/Next button.
https://user-images.githubusercontent.com/814828/220464863-657b1977-43ed-4c4a-b8ba-b2c1fcc71625.mov
https://user-images.githubusercontent.com/814828/220464908-c4a5be5d-3323-42d7-8552-661f326ce3ee.mov
> Fixed schedule info when using Prev/Next button

- client/components/cards/BookMatchCard.vue
- client/components/cards/LazyBookCard.vue
- client/components/modals/item/tabs/Match.vue
- client/components/modals/podcast/NewModal.vue
- client/components/widgets/ExplicitIndicator.vue
- client/pages/item/_id/index.vue
- client/pages/library/_library/podcast/latest.vue
- client/pages/library/_library/podcast/search.vue
- server/providers/iTunes.js
The language and explicit information aren't imported when you search for a podcast and add it to the library.
This pull request fixes this and adds an explicit indicator when a podcast/book has the explicit field checked (similar to what Apple Podcasts does).
A component (widget) was created to use the same explicit indicator style.
**Importing Explicit and Language Info**
**Add explicit info when matching an existent item**
**Apple Podcasts explicit label**
**Explicit label on the contents**
**Works for books as well**
> Fixed explicit/language info import and added Explicit indicator

- client/components/modals/podcast/NewModal.vue
- client/components/modals/podcast/tabs/EpisodeDetails.vue
- client/components/widgets/PodcastDetailsEdit.vue
- client/store/globals.js
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/fr.json
- client/strings/hr.json
- client/strings/it.json
- client/strings/pl.json
- client/strings/ru.json
- client/strings/zh-cn.json
- server/objects/Feed.js
- server/objects/FeedEpisode.js
- server/objects/FeedMeta.js
- server/objects/entities/PodcastEpisode.js
- server/objects/metadata/PodcastMetadata.js
- server/scanner/Scanner.js
- server/utils/podcastUtils.js
To make the RSS Feed more compliant with the RSS Feed standards, I created this pull request to add:
- Add a podcast type field <_itunes:type_> - Episodic (default) or Serial
- Add a dropdown with the episode types <_itunes:episodeType_> - Full, Trailer, Bonus
- Add Season, Episode number, Episode Type and Podcast Type on the Feed - <_itunes:season_>, <_itunes:episode_>, <_itunes:episodeType_> and <_itunes:type_>
- Use language information from the Item for the language tag. If the item doesn't have language information use "_en_" as default. - <_language_>
----
**Context:**
I researched to identify the Podcast Types and Episodes Types patterns used by iTunes Podcast, Google Podcast, and other providers. All open services use the same pattern informed by [Apple - A Podcaster’s Guide to …
> Adding podcast type, season and episode info to the feed

- client/components/cards/BookMatchCard.vue
- client/components/cards/LazyBookCard.vue
- client/components/widgets/AlreadyInLibraryIndicator.vue
- client/components/widgets/ExplicitIndicator.vue
- client/pages/item/_id/index.vue
- client/pages/library/_library/podcast/latest.vue
- client/pages/library/_library/podcast/search.vue
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/fr.json
- client/strings/hr.json
- client/strings/it.json
- client/strings/pl.json
- client/strings/ru.json
- client/strings/zh-cn.json
This pull request improves the Explicit indicator by adding a tooltip with the description.
And on the search podcast page, add a new indicator when the search returns already-added podcasts (comparing by iTunes ID or Name).
---
> Improve explicit label and add a AlreadyInYourLibrary indicator

- server/objects/FeedMeta.js
#1554 was way better than what I could do, had 1 minor issue. iTunes:block should be "Yes". Any other result is ignored. [Documentation here](https://help.apple.com/itc/podcasts_connect/#/itcb54353390). Although I cannot find the documentation for google:block, pattern podcast feeds suggest it should be lowercase "yes".
> Fix incorrect tags when blocking public feeds

- client/components/widgets/AlreadyInLibraryIndicator.vue
- client/pages/library/_library/podcast/search.vue
This pull request improves the podcast search when the results contain existing podcasts in your library.
- The Already in your library indicator is green to make more highlighted
- If you try to add a podcast already in your library, the action is changed to redirect you to the existing podcast page.
----
https://user-images.githubusercontent.com/814828/221650426-6302a244-cfb1-43a4-97ba-de133c88c4bc.mov
> Improve podcast search

- client/components/modals/podcast/EditEpisode.vue
- client/components/modals/podcast/tabs/EpisodeDetails.vue
- client/components/tables/podcast/EpisodesTable.vue
- client/components/ui/RichTextEditor.vue
- client/store/index.js
- server/controllers/PodcastController.js
- server/routers/ApiRouter.js
This pull request adds a new action to save podcast editing without closing the modal.
- Like the Library Item editing, we have two buttons, Save and Save & Close actions.
- `Save` button updates the episode and keeps the modal opened
- `Save & Close` updates the episode details and closes the modal
- I also added chevron buttons to navigate to the next or previous episode to make editing many episodes in sequence easier.
----
> Improve podcast editing

- server/utils/parsers/parseNameString.js
#793
Duplicate "&" style multi author/narrator support for semicolon. I did consider a loop for handling separators, but it seems like overkill, however happy to be persuaded.
> Support for scanning semicolon seperated author and narator lists.

- client/components/modals/item/tabs/Cover.vue
- client/store/scanners.js
- server/finders/BookFinder.js
- server/providers/AudiobookCovers.js
I recently launched [AudiobookCovers.com](audiobookcovers.com). [Source code and documentation](https://github.com/Weldawadyathink/Audiobook-Covers). The goal of the project is to archive all the audiobook covers posted to [/r/audiobookcovers](reddit.com/r/audiobookcovers), and make them searchable using google vision optical character recognition. 
This pull request adds support for AudiobookCovers.com as a metadata provider. Unlike other metadata providers, it only provides cover images. Therefore, this PR also allows providers to be listed only in the covers modal, so the new provider will not be listed under match or the library config screens.
> Add AudiobookCovers.com metadata provider

- server/utils/prober.js
Since `part` is a supported tag for `m4b` files, it's now added as another fallback option.
Reference: https://github.com/advplyr/audiobookshelf/issues/787#issuecomment-1532282307
> Added `part` to supported tags for `file_tag_seriespart`

- readme.md
After setting up the reverse proxy for Apache per the current instructions, I received the error:
> AH01144: No protocol handler was valid for the URL / (scheme 'http')
Installing `proxy_http` and `proxy_balancer` modules in addition to those listed (as recommended [here](https://stackoverflow.com/a/26045183)) fixed this issue.
`a2enmod` command does not include the redundant `_module` suffix.
Let's Encrypt was not able to validate certificates either automatically or manually as ABS does not respond to ACME challenges directly. Editing the virtual environment configuration to not reverse-proxy `/.well-known`, and serving that directly from Apache allowed LE to validate the challenge.
> Update readme.md - Expand required Apache modules for reverse proxy and detail how to handle acme challenges

- server/Server.js
> Fix: useTempFiles=true, upload use tmp instead of ram

- server/utils/parsers/parseOpfMetadata.js
Found this while importing some bad opf data into my library. Spent some time going through the parseOpfMetadata class and saw that it allows this on a few fields. I'm not a js expert, so please let me know if you want me to refactor the changes I made.
> stop opf importer from adding duplicate info

- server/utils/fileUtils.js
Right now ABS converts `206291193b` into `196.73MB`. This is only partially correct, because the bytes are converted using a factor of 1024. The correct amount would be `206.29MB` The are converted to [Mebibyte](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units) not Megabytes. I got confused by it, because if was wondering why my file size did not match with the one I uploaded. Changing the factor to 1000 fixes this. The unit could also be renamed to `MiB` but I think this would only confuse most people.
And yes linux used Mebibyte here, but they do it throughout the entire system. My supposed 5TB Hard drive shows up as a 4.5TB one, because it is only technically 5TB large. Actually it has only 4.5TiB of usable space. But I think this is trivial, as most people probably don't use the …
> Fix byte conversion

- .gitignore
- server/managers/BackupManager.js
If the backup file is not a valid .zip file, or the .zip file is corrupted the server crashes. 
This catches the error and returns an error description to the user
> Fix: server crash when uploading invalid backup file

- docker-compose.yml
The example docker compose file in github does not have the podcasts volume in it, unlike on [the official website](https://www.audiobookshelf.org/docs#docker-compose-install).
> Added podcasts volume to docker compose

- build/debian/DEBIAN/preinst
Extract ffmpeg and tone but ignore the ownership information from the tar archive. This will ensure that those files are owned by root, not the UIDs/GIDs the tar files happen to contain.
> Fix system file ownership for Debian package

- server/utils/parsers/parseFullName.js
I noticed the following crash in my server:
```
/server/utils/parsers/parseFullName.js:73
nameParts[j].slice(-1) !== '.' &&
^
TypeError: Cannot read properties of undefined (reading 'slice')
at fixParsedNameCase (/server/utils/parsers/parseFullName.js:73:28)
at module.exports (/server/utils/parsers/parseFullName.js:344:16)
at parseName (/server/utils/parsers/parseNameString.js:9:15)
at /server/utils/parsers/parseNameString.js:81:20
at Array.forEach (<anonymous>)
at Object.module.exports.parse (/server/utils/parsers/parseNameString.js:80:18)
at /server/scanner/BookScanner.js:650:54
at Array.forEach (<anonymous>)
at BookScanner.getBookMetadataFromScanData (/server/scanner/BookScanner.js:640:24)
at BookScanner.rescanExistingBookLibraryItem (/server/scanner/BookScanner.js:172:37)
```
When I …
> Fix typo in fixParsedNameCase

- server/controllers/BackupController.js
- server/controllers/LibraryItemController.js
- server/managers/CacheManager.js
- server/utils/fileUtils.js
updates util function  encodeUriPath to use node:url with a file:// path prefix, and updates all instances x-accel redirection to use this helper util instead of sending unencoded paths into the header.
Using a local dev container with an external nginx reverse proxy for x-accel: I tested covers, audio files, and ebooks which all played correctly, even with unicode chars. I was unable to get download working, but I think that was just because of my test setup. I don't see any reason it should function differently in a proper setup...
fixes errors such as:
```
[2023-09-16 22:46:05] DEBUG: Use X-Accel to serve static file /audiobooks/Craig Alanson/Ascendant/1. Ascendantː Book 1/Ascendantː Book 1.webm (LibraryItemController.js:578)
node:internal/errors:478
ErrorCaptureStackTrace(err);
^ …
```
> [server] x-accel: encode all paths to URIs

- client/components/modals/item/tabs/Match.vue
In the Match tab, the Search Title and Author are not properly encoded, therefore if any of them contains an ampersand character, the generated search URL will be incorrect. This is resolved by encoding them using encodeURIComponent.
Resolves #2128
> Use encodeURIComponent for text inputs in Match.vue

- server/finders/BookFinder.js
- server/scanner/Scanner.js
Problem:
Audiobookshelf requires a pretty strict folder structure. However, users sometimes have many books in existing folders that adhere to different (or no) standards, and they might be reluctant to fix their directory structure. But then book titles and authors are incorrectly read, and consequently, matching usually return no/wrong results, which requires users to manually fix the title and author before matching.
The option to prefer audio metadata over folder names somewhat improves the situation, but does not fix it, and is also not enabled by default.
Proposal:
As a first step, I'd like to suggest a heuristic fuzzy matching, that kicks in if the initial title and author search returns no results (a rudimentary version of this already exists in the code, potentially sending one …
> Fuzzy Matching V1

- server/Database.js
I've been doing some debugging of Sqlite query performance, and I found it useful to enable logging of DB queries as they happen, so I figured I'd send a PR in case it's useful to others as well.
Logging all queries is pretty noisy, so rather than just logging at some log level, I've gated this logging behind a `QUERY_LOGGING` environment variable. Set it to `QUERY_LOGGING=log` to log just the query. Set it to `QUERY_LOGGING=benchmark` to log both the query and how long it took to run.
I'm happy to switch to some other mechanism for enabling this, if using an env var is undesirable.
An example benchmarking log message would look like this:
```
[2023-09-15 05:57:48] DEV: Ran the following query in 3ms:
Executed (default): SELECT `podcast`.`id`, `podcast`.`title`, COUNT('*') AS …
```
> Add ability to enable DEV logs of Sqlite queries

- server/Watcher.js
- server/utils/fileUtils.js
Fixes #2244.
This fix applies [this solution](https://stackoverflow.com/questions/37521893/determine-if-a-path-is-subdirectory-of-another-in-node-js) to perform proper subpath checking.
> Fix incorrect subpath checks in server/watcher.js

- client/components/readers/EpubReader.vue
- client/components/readers/Reader.vue
- client/strings/da.json
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/fr.json
- client/strings/gu.json
- client/strings/hi.json
- client/strings/lt.json
- client/strings/nl.json
- client/strings/no.json
- client/strings/pl.json
- client/strings/ru.json
- client/strings/zh-cn.json
Adds an option to switch between serif and sans-serif fonts in the epub viewer.
Translations are machine translated.
> Option to change the font family in epub viewer

- server/controllers/MiscController.js
- server/routers/ApiRouter.js
This adds a an API for notifying the server of an update to a watched library folder. Each call to the API essentially mimics a watcher event, and calls the same event listener that listens to real watcher events.
It is meant to be used by an external watcher (e.g. one that would run on a Docker host), in an attempt to mitigate #2204 (watcher not firing events when watching bind mounts on docker). I'm currently working on such an external watcher that could be run on node.js on the docker host and which will use this API. Hopefully this external watcher can also be packaged as an executable, and could be installed as a service on the host machine.
> Add API to update a path on a watched library folder

- client/components/app/StreamContainer.vue
- client/components/covers/BookCover.vue
- client/components/modals/RawCoverPreviewModal.vue
- client/layouts/default.vue
- client/pages/item/_id/index.vue
- client/store/globals.js
This makes it so that clicking on the cover in the item view or the player bar brings up a modal with an enlarged view of the cover so we can see all the juicy details of high-res covers.
Closes #1853
> show a modal with cover images when clicked

- client/components/readers/EpubReader.vue
- client/components/readers/Reader.vue
- client/components/ui/TextInput.vue
Adds a search box in the table of contents sidebar to search for text within epubs.
Search results are displayed under the chapter they are found in, but at the moment, only the first two chapter levels are displayed in the ToC, so search results in chapters more than two levels deep won't appear. I could see about using a recursive component to display ToC entries instead, although I haven't found a book with more than three chapter levels yet.
This also makes adds a flattenChapters method, which converts ebook chapters into something that looks like audiobook chapters so that the seek bar will work with ebooks too (in a future pull request)
Closes #2045
> Search epub text

- server/Server.js
- server/objects/Feed.js
- server/objects/FeedEpisode.js
Following my [enhancement request](https://github.com/advplyr/audiobookshelf/issues/2263) to add support for an old version (1.2.3) of the Apple Podcasts iOS app, I found that the RSS feed needed:
1. the artwork URL to include the file extension;
2. the audio file URL not to contain any non-ASCII character and to include the file extension.
With this patch:
1. The artwork URL on the RSS feed now includes the artwork file extension.
2. The content URL does not contain anymore the full filename (`/feed/${slug}/item/${episode.id}/${episode.audioFile.metadata.filename}`) but is now generic keeping a correct file extension (`/feed/${slug}/item/${episode.id}/media${contentFileExtension}`).
Feel free to comment or suggest any prettier code, I digged recently into this project.
> Add support for the old Apple Podcasts iOS app

- server/scanner/LibraryScanner.js
Resolves #2282.
After the fix, relevant logs lines:
```
[2023-11-04 11:03:26] DEBUG: [Watcher] File Added /torrents/2BR02B - librivox.m4b (Watcher.js:151)
[2023-11-04 11:03:26] DEBUG: [Watcher] Modified file in library "Torrents" and folder "7574feec-eebc-4858-a01e-7613f1eac121" with relPath "/2BR02B - librivox.m4b" (Watcher.js:256)
[2023-11-04 11:03:26] DEBUG: [Watcher] Waiting to add file at "/torrents/2BR02B - librivox.m4b". mtimeMs=1696863726581.3113 lastMTimeMs=0 (loop 0) (Watcher.js:209)
[2023-11-04 11:03:27] DEBUG: [Watcher] File finished adding at "/torrents/2BR02B - librivox.m4b" (Watcher.js:205)
[2023-11-04 11:03:30] DEBUG: [Scanner] Scanning file update groups in folder "7574feec-eebc-4858-a01e-7613f1eac121" of library "Torrents" (LibraryScanner.js:459)
[2023-11-04 11:03:30] …
```
> Fix handling of single media file updates

- client/components/tables/collection/BookTableRow.vue
This fixes #2278 by hiding the duration of a book in a collection if it is 0 (or less). I suppose some audiobooks could also have a duration of 0, but this seems rare (and perhaps hiding the duration in those cases also makes sense?). I opted not to go with progress as that would result in the value having different meanings depending on the media type, which sounds like a potentially confusing user experience.
While this fixes the reported bug, I wonder if it makes sense to have page count as the "duration". Although that would require more effort to implement I think.
> Hide collection duration if 0

- server/Logger.js
This patch adds milliseconds to the time string used for logging. This helps when debugging some timing issues and should have no real negative side effect.
> Add milliseconds to logging

- server/Logger.js
This patch allows users to enable dev logs on production systems by setting the `HIDE_DEV_LOGS` environment variable.
Before, you could only use this on a non-production environment. On production, the logs would be disabled. This patch changes the behavior and uses the `NODE_ENV` only as default. On production they are disabled if `HIDE_DEV_LOGS` is undefined but can be enabled by setting `HIDE_DEV_LOGS=0` on dev, they are enabled if undefined, but can be disabled by setting `HIDE_DEV_LOGS=1`.
> Allow enabling dev logs

- readme.md
Updated the docs for synology reverse proxy to match the current version of synology DSM (7.x). Current docs show settings for outdated DSM 6.x
> docs: update synology reverse proxy to use the latest DSM settings

- client/components/readers/ComicReader.vue
I am enjoying audiobookshelf very much, I recently added some comics to my collection and they are hard to read in my laptop due to the lack of zoom.
I managed to enable zoom (by modifying the width of the <img> tag) to the comicreader without external dependencies.
I am open to discuss other possibilities if that is what you prefer, screenshot:
> Add zoom controls to comic reader

- server/scanner/OpfFileScanner.js
- server/utils/parsers/parseOpfMetadata.js
- test/server/utils/parsers/parseOpfMetadata.test.js
I see that some people like me using this software are missing multiple series in OPF file.
```xml
<meta name="calibre:series" content="Serie 1"/>
<meta name="calibre:series_index" content="1"/>
<meta name="calibre:series" content="Serie 2"/>
<meta name="calibre:series_index" content="2"/>
```
so here it is, along with unit tests.
> Add: OPF file supports multiple series as sequence of : calibre:series and calibre:series_index; including tests

- server/Server.js
I've noticed that once in a while (can't reproduce consistently), when hitting Ctrl+C to close ABS, the port is not properly released, and the next time I start the server I get EADDRINUSE error. I'm not sure what's the reason for that, but I thought adding a SIGINT handler that calls the server's stop method would be good practice anyway, and It would also provide a way for proper stopping in the upcoming Windows tray app.
I implemented this like many standard SIGINT handlers - the first SIGINT waits for server stop, the second exits immediately (the current behavior).
> Add a SIGINT handler for proper server shutdown

- server/Server.js
- server/SocketAuthority.js
This is a small fix for my previous PR #2445.
If there are connected SocketIO sockets, then calling server.close() on SIGINT will hang and not resolve.
Instead, we need to call SocketAuthority.io.close(), which will disconnect all connected sockets, and also close the underlying http server (see documentation [here](https://socket.io/docs/v4/server-api/#serverclosecallback)). Sorry for missing this initially.
> Add SocketAuthority.close()

- server/utils/fileUtils.js
Added a try/catch to the fileUtils.js getFileMtimeMs function.  This addresses the exception thrown when an ephemeral file is added to a library and flagged by Watcher to be scanned.   I tested this against 2.6.0 and 2.7.0 and it resolves my situation mentioned in https://github.com/advplyr/audiobookshelf/issues/2332 and it should resolve the reported issue completely.
> Add try/catch to fileUtils.getFileMtimeMs

- Dockerfile
This PR adds `tini` to the container image and uses it as PID 1 when starting the container.  This ensures that proper PID 1 signal-handling is implemented and passed to the underlying node.js process, thereby ensuring that the ABS process has a chance to receive and handle signals other than `SIGKILL`, such as the important `SIGINT`.
This is somewhat related to #2445 . Without this, the signal handled by 2445 won't be received when running in a container.
Some background:
In linux, PID 1 has special duties involving signal handling that are different than other processes.  Node doesn't properly handle these signals, which can lead to a number of problems ranging from annoying to disruptive.  PID 1 also has reaping duties that can lead to resource exhaustion if not properly handled.
For …
> Add tini as PID 1 handler in container image

- server/Database.js
- server/Logger.js
- server/models/Library.js
- server/models/LibraryItem.js
Change `Logger.dev` calls to `Logger.debug`
`Logger.dev` is kind of in a weird spot where it doesn't fit into the
standard log level.  It is called directly by some code and it only
checks whether a property is set (which comes from an env var) before
deciding to print out.
This standardizes on `debug` by changing the dev calls to debug. Also
removes the now unused code.
> Change `Logger.dev` calls to `Logger.debug`

- server/providers/AudiobookCovers.js
Changes AudiobookCovers.com provider to return the full size png file from the server. The original file url has the incorrect content-type header set, which caused issues downloading new cover images.
> Return png from AudiobookCovers.com

- server/Logger.js
The logger should include a source containing the location where the logger was called. This works well for logging to `stdout`. Unfortunately, the file logs contain the locations where the file logging is called inside of the logger. This is not helpful:
```
{"timestamp":"2023-11-19 16:35:43","source":"Logger.js:114","message":"[oldDbFiles] Processed db data file with 1 entities","levelName":"INFO","level":2}
{"timestamp":"2023-11-19 16:35:43","source":"Logger.js:114","message":"[oldDbFiles] Finished loading db data with 2 entities","levelName":"INFO","level":2}
{"timestamp":"2023-11-19 16:35:43","source":"Logger.js:114","message":"[oldDbFiles] 2 settings loaded","levelName":"INFO","level":2}
```
This patch fixes the issue, ensureing that the actual source location will be logged:
``` …
```
> Fix log source in log file

- client/components/modals/item/tabs/Match.vue
- client/pages/library/_library/podcast/latest.vue
- server/controllers/LibraryItemController.js
This adds client-side caching for book and podacst cover images.
Caching is performed only for timestamped requests, with cachce-control header set to 'private, max-age=86400'. This means:
- Caching is only done on the client, and not in any proxies. I chose this because currently the URL contains the authorization token, which somewhat of a security flaw, and also makes caching useful only for a specific client and user.
- Caching TTL is one day. Later we can add 'immutable', since the timestamp is updated when the image changes on the server, so cache-busting is possible.
Most important cases in which cover images are displayed on the client already have server-originated timestamp (updatedAt). I [updated a couple of places](https://github.com/advplyr/audiobookshelf/commit/4fe672f09d794c …
> Client side cover image caching

- client/components/ui/MultiSelect.vue
- client/components/ui/MultiSelectQueryInput.vue
Fixes #2700 (see details in the bug).
Note that setInputWidth was removed, and with it the call to this.RecalcMenuPos(). 
I'm not sure why this call is required. If it is, let me know and I'll try to re-incorporate it where it makes sense.
> Fix input width in MultiSelect UI components

- server/utils/fileUtils.js
This patch ensures that files names like `series #3 xy.jpg` are actually handled correctly instead of the part after `#` being interpreted as fragment and being discarded.
I noticed that in a few rare cases the App wouldn't properly display cover images. It turns out that due the file names containing a `#`, the file path got corrupted, causing Audiobookshelf to return a 403.
---
To reproduce the issue (there are likely more ways):
1. Enable XAccel, e.g. by putting in the `docker-compose.yml` (even if you don't configure Nginx for this, you should still be able to confirm the issue):
```yml
audiobookshelf:
image: ghcr.io/advplyr/audiobookshelf:2.8.0
environment:
- USE_X_ACCEL=/protected
```
2. Upload a book with a path that includes a `#` like `/data/audiobooks/Author/Series #1 - …
> Fix file names with URL control characters

- server/finders/BookFinder.js
- server/providers/CustomProviderAdapter.js
This adds the isbn to the CustomProviderAdapter so that it can be used as a identifier like the asin is used by Audible.
> Added isbn to CustomProviderAdapter

- server/providers/Audible.js
- test/server/providers/Audible.test.js
Fixes #2710.
The fix makes the sequence cleanup a bit less aggressive, so that the sequence number, which translates to: "first-season : 1", does not get trimmed to "first-season". 
The fix to #2380 still works.
> Make series sequence cleanup slighlty less aggressive

- client/components/modals/libraries/EditModal.vue
- client/components/modals/libraries/LibrarySettings.vue
- client/strings/cs.json
- client/strings/da.json
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/et.json
- client/strings/fr.json
- client/strings/gu.json
- client/strings/hi.json
- client/strings/hr.json
- client/strings/hu.json
- client/strings/it.json
- client/strings/lt.json
- client/strings/nl.json
- client/strings/no.json
- client/strings/pl.json
- client/strings/pt-br.json
- client/strings/ru.json
- client/strings/sv.json
- client/strings/vi-vn.json
- client/strings/zh-cn.json
- server/models/Library.js
- server/objects/settings/LibrarySettings.js
- server/utils/queries/libraryFilters.js
- server/utils/queries/libraryItemsBookFilters.js
Closes https://github.com/advplyr/audiobookshelf/issues/2687 on merge.
* Are there any linting rules I should make sure I follow?
* Did I miss running some script for the other translations?
* Does anyone know of a better name than `onlyShowLaterBooksInContinueSeries` for the setting variable name?
* Does anyone have better copy suggestions for the toggle + info text?
<details>
<summary>Picture in library, second book read, third up next (first is unread but not next in continue series)</summary>
</details>
<details>
<summary>Book 2 and 3 read, book 1 still not showing up in Continue Series</summary>
</details>
<details>
<summary>Library settings page</summary>
</details>
> Add library toggle setting for skipping earlier instalments in Continue Series

- .github/workflows/unit-tests.yml
This is pretty self-explanatory:
- Trigger on pull_request or push (can also run manually on any ref)
- Checkout
- Run npm ci
- Run npm test
> Unit tests flow

- .github/workflows/unit-tests.yml
Separates workflow_dispatch and non-workflow_dispatch checkouts into two separate conditional steps.
The initial workflow in PR #2745 was broken when triggered by pull requests.
> Change unit tests workflow to include conditional checkout steps

- server/Logger.js
- server/models/LibraryItem.js
- server/scanner/BookScanner.js
- server/scanner/LibraryItemScanData.js
- server/scanner/LibraryItemScanner.js
- server/scanner/LibraryScanner.js
- server/scanner/PodcastScanner.js
Fixes #2686 
After some further investigation, it looks like the code already covers Audio files media updates for modified files, so what I ended up doing was the following:
- Refactored library files properties in LibraryItemScanData
- Used the refactored properties above in BookScanner and PodcastScanner to update media with modified ebook/cover library files
- Fixed another related bug in which libraryFolderId in LibraryItem was also not properly updated when books were moved between different library folders within the same library
To test this, I did a lot of moving of directries between different folders (with audio/ebooks/covers) in the same library ) with watcher on and off (and running library scans when watcher was off). Now everything seems to be working without crashes or …
> Fix library files inconsistencies

- server/finders/BookFinder.js
The method `search(title, author, isbn, providerSlug, mediaType)` (`CustomProviderAdapter#17`) expects five arguments but only receives four. This causes a crash because no custom metadata provider `book` (passed as forth argument, not fifth) does exist
> Fix custom metadata provider crash

- server/utils/queries/libraryItemsBookFilters.js
Currently the Continue Series shelf (with skip earlier books toggle active) returns some weird results if you have more than 10 series which has a read book, but not all of them have a book that qualifies for the constrains of being of a higher sequence number than the ones already finished.
This is because the sql query returns the 10 series with most recent progress that fit for the untoggled library setting.
In order to solve the issues caused by this, I added the same sql query that calculates the `maxSequence` number to the original where-query, so that it will only return series that we know has books in them that are of a higher sequence than the ones already read.
The post-query code is still there, since the query still returns books that are below the `maxSequence` number. …
> Fix book limit for the Continue Series shelf (with skip earlier books toggle active)

- .github/workflows/notify-abs-windows.yml
This workflow dispatches an event to the windows repository (mikiher/audiobokshelf-windows) when a new server release is published. 
The event triggers a [workflow](https://github.com/mikiher/audiobookshelf-windows/blob/d187b3de24c2ab7b5e095f131e3d59b66c0ca657/.github/workflows/build-installer.yml#L4) on the windows repository that builds a new windows installer with the latest server release, and creates a draft release for it (this was done manually up until now).
In order for it to work, you'll need to add a secret in the server repository named ABS_WINDOWS_PAT, which will contain the private access token needed to dispatch the event. I sent the token to you in a Discord PM.
> Workflow to dispatch an ABS windows event on server release

- client/components/cards/LazyBookCard.vue
- client/components/modals/item/tabs/Episodes.vue
- client/components/modals/podcast/ViewEpisode.vue
- client/components/tables/ChaptersTable.vue
- client/components/tables/podcast/DownloadQueueTable.vue
- client/components/tables/podcast/LazyEpisodeRow.vue
- client/components/ui/TextInput.vue
- client/components/ui/TextareaInput.vue
- client/pages/item/_id/index.vue
- client/pages/library/_library/podcast/latest.vue
This adds dir="auto" attribute to some text elements, in which it makes sense to modify the display when the text is in a RTL language (e.g. Arabic, Hebrew, Urdu, etc.)
The change has no effect on LTR text. The main visible difference in RTL text is that it is naturally aligned to the right (and there are also some subtler differences in the rendering of mixed text containing both RTL and LTR characters).
Some examples after the change:
In the Latest Episodes page:
In the Recently Added row on the Homepage:
You can see in both examples how Hebrew text is right-aligned (as expected), while English text remains as-is.
*Note*: this is *not* an attempt at full RTL support for the Hebrew locale (which will likely require more work).
> Add dir="auto" attribute where RTL display is needed

- client/pages/item/_id/index.vue
If a book is part of multiple series, this patch adds a separator between the series on the library item details page. With no separator, it is not immediately clear that they are separate series.
> Separator between multiple series

- client/components/modals/ListeningSessionModal.vue
- client/pages/config/sessions.vue
- client/pages/config/users/_id/sessions.vue
Right now the client name is not visible in the `Device Info` section of a listening session, this PR adds it a possible line
> Add client name to possible device info lines

- client/components/modals/item/tabs/Match.vue
- client/strings/bn.json
- client/strings/cs.json
- client/strings/da.json
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/et.json
- client/strings/fr.json
- client/strings/gu.json
- client/strings/he.json
- client/strings/hi.json
- client/strings/hr.json
- client/strings/hu.json
- client/strings/it.json
- client/strings/lt.json
- client/strings/nl.json
- client/strings/no.json
- client/strings/pl.json
- client/strings/pt-br.json
- client/strings/ru.json
- client/strings/sv.json
- client/strings/uk.json
- client/strings/vi-vn.json
- client/strings/zh-cn.json
- client/strings/zh-tw.json
This PR fixes https://github.com/advplyr/audiobookshelf/issues/2889.
Adds 4 pixels in between the two cover images, and adds "Select All" translatable text for the top checkbox.
> Book match tab update

- server/controllers/LibraryController.js
- server/utils/queries/authorFilters.js
Currently on the library stats page, the function getAuthorsWithCount() is called to get both the top 10 authors by number of books, and also the total number of authors in that library. It does this by querying for all authors and every related book. In a library of 30k authors, this query takes `567038ms`  or around 10 minutes.
This has been split into 2 calls - getAuthorsTotalCount() gets the total number of authors in the library in `1ms` and getAuthorsWithCount() only grabs the top 10 authors by number of books written in `35ms`. These values will vary based n the number of books in the library, but it represents a significant speed increase.
The results displayed on the stats page should be identical after the change.
> Split the author call in the library stats page to 2 lighter functions

- client/pages/config/log.vue
- client/strings/bn.json
- client/strings/cs.json
- client/strings/da.json
- client/strings/de.json
- client/strings/en-us.json
- client/strings/es.json
- client/strings/et.json
- client/strings/fr.json
- client/strings/gu.json
- client/strings/he.json
- client/strings/hi.json
- client/strings/hr.json
- client/strings/hu.json
- client/strings/it.json
- client/strings/lt.json
- client/strings/nl.json
- client/strings/no.json
- client/strings/pl.json
- client/strings/pt-br.json
- client/strings/ru.json
- client/strings/sv.json
- client/strings/uk.json
- client/strings/vi-vn.json
- client/strings/zh-cn.json
- client/strings/zh-tw.json
Fixes https://github.com/advplyr/audiobookshelf/issues/2932
> Add: logs documentation

- client/components/ui/TimePicker.vue
Fixes https://github.com/advplyr/audiobookshelf/issues/2685
Original behavior was that the TimePicker.vue template was not targetable by a tab. I added a tab target and set the ones place of the seconds to be the default starting point. Currently, users can also tab out of the TimePicker and be focused on two elements, so that is also fixed in this PR.
Original behavior:
https://github.com/advplyr/audiobookshelf/assets/5686638/963ced40-ab9f-46d4-9042-8d1b35d83424
New behavior:
https://github.com/advplyr/audiobookshelf/assets/5686638/b352e903-503e-4715-934c-7ca377c1267d
> Time picker cleanup

- client/components/tables/playlist/ItemTableRow.vue
- client/pages/playlist/_id.vue
Fixes: https://github.com/advplyr/audiobookshelf/issues/3016
Do not hide the "edit" or "delete" key on the playlist page even if users do not have "Can Update" permission because they are private structures, so editing does not affect other users.
User without edit permissions view:
> Users can edit playlist in UI

- client/components/modals/item/tabs/Match.vue
- client/components/ui/MultiSelect.vue
Used the multi-select behavior that exists on Genres in Match to work on Narrators and Tags.
> Change Tags and Narrators to work the same as Genres on the Match page.

- server/utils/fileUtils.js
The recent commit to support disabling the ssrfFilter has broken url loading for non podcasts due to a copy paste error from the podcasts file. This switches the `feedUrl` back to the original `url` and makes image loading, and my kid waiting on a new audiobook, happy.
The original issue likely had a few ways to trigger it but in my scenario it was updating an audiobooks metadata and replacing the image, the error in the logs was:
```
[Server] Unhandled rejection: ReferenceError: feedUrl is not defined, promise: Promise { <rejected> ReferenceError: feedUrl is not defined at /snapshot/audiobookshelf-git/server/utils/fileUtils.js at new Promise (<anonymous>) at Object.downloadFile (/snapshot/audiobookshelf-git/server/utils/fileUtils.js) at …
```
> Fix ssrfFilter url

- .github/workflows/i18n-integration.yml
This PR updates the localization workflow to `1.3.0`. This version removes the unused copying of keys to speed up the workflow, and changes the alphabetical check to be case sensitive to conform to Weblate.
> Update i18n workflow to `1.3.0`

- server/utils/parsers/parseOverdriveMediaMarkers.js
Fixes https://github.com/advplyr/audiobookshelf/issues/3068
The `generateParsedChapters` did not include the hours part of the timestamp.
> Time parsing fix

- server/managers/PlaybackSessionManager.js
I'm not sure exactly the situation which creates this, but there is an if statement which checks if `itemProgress` -- but then uses it even if not. This caused my server to become useless recently =] Simple fix.
> bug: If !itemProgress unhandled exception syncing user progress

- docs/controllers/AuthorController.yaml
- docs/controllers/LibraryController.yaml
- docs/openapi.json
- docs/schemas.yaml
This PR updates some of the `requestBody` to `parameters` and creates some generic `parameter`s in response to changes made in https://github.com/advplyr/audiobookshelf/commit/d6438590d7010e9e9f512ecfdbf4cd7f0d149407
This PR also allows for reserved characters (commas) to be included in select query parameters.
> Change: `requestBody` to `parameter`, allow commas in queries

- server/utils/ffmpegHelpers.js
- server/utils/fileUtils.js
- server/utils/podcastUtils.js
Hey folks, I work on Pinecast (https://pinecast.com). We recently had a customer write in that their audiobookshelf server stopped updating feeds from us. It turns out that we'd seen a huge uptick in requests from the default Axios user agent string, which caused requests with that user agent to get served a captcha. My suspicion is that companies have started scraping more aggressively.
Podcast apps have (by and large) done a good job of providing descriptive `User-Agent` headers. Identifying your app allows podcasters to get informed analytics data and helps hosting companies like mine to identify and fix problems more easily.
---
In this PR, I'm adding the `user-agent` HTTP request header. I've chosen a value that is fairly straightforward: the name of the project, a link to the …
> Add user agent string to feed requests

- server/scanner/LibraryScanner.js
I'm not sure how it got into this state, but once in the state it keeps crashing. Might be because I have multiple instances running against the same sqlite database so two concurrent were scanning at the same time?
> bug: if oldLibraryItem is null things crash

- client/components/tables/BackupsTable.vue
- client/pages/config/backups.vue
- client/strings/en-us.json
- server/controllers/BackupController.js
- server/managers/BackupManager.js
- server/objects/settings/ServerSettings.js
This PR prevents the backup path from being edited in the web interface if the `BACKUP_PATH` environment variable is set. This is done to help prevent users from thinking their backup settings are not being applied correctly if they are not looking at the debug logs on server start as mentioned here https://github.com/advplyr/audiobookshelf/issues/2973#issuecomment-2179518347.
I changed the response for a `GET` request to `/api/backups` to include an additional value of whether this field can be editable, and set this value in the server settings in the same places where the ENV variable is checked.
Tested with setting and removing the ENV variable to make sure that the field is then editable.
View with environment variable not set:
View with environment variable set:
> Prevent backup path edits when ENV is set

- .github/workflows/integration-test.yml
- build/linuxpackager
- package.json
- server/Server.js
This replaces the use of pkg (which packs Node runtime and project code into a single binary) with the @yao-pkg/pkg fork. We do this since pkg is deprecated and in maintenance mode, and doesn't support packing a node20 runtime. Yao-pkg seems to be well maintained and used, and supports node20 targeting.
Changes made:
- Replace node18 pkg targets with node20
- Modify relevant workflows and scripts to install @yao-pkg/pkg instead of pkg
- Log Node version when server goes up for clarity
> Replace pkg with @yao-pkg/pkg and target node20

- server/utils/parsers/parseOpfMetadata.js
This fixes #3123.
The fix just deduplicates the series extracted from the epub's OPF (that's the only real change - all others are due to formatting being applied).
> Fix OPF fetchSeries so it deduplicates found series

- client/components/app/BookShelfCategorized.vue
This adds a simple viewport condition when fetching the personalized shelve data for the home page, so screens with larger aspect ratios, such as 21:9, don't have space on the right side.
This resolves #2518
> Add ultrawide support for home page

- client/pages/config/backups.vue
- client/strings/en-us.json
- server/managers/BackupManager.js
- server/objects/settings/ServerSettings.js
This MR adds support for allowing backups of unlimited size (denoted by 0).
Addresses #3157
> Adds support for allowing backups of unlimited size

- client/components/cards/AuthorSearchCard.vue
- client/components/cards/GenreSearchCard.vue
- client/components/cards/NarratorSearchCard.vue
- client/components/cards/TagSearchCard.vue
- client/components/controls/GlobalSearch.vue
- client/components/ui/LibrariesDropdown.vue
- client/pages/library/_library/search.vue
- client/strings/en-us.json
- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
Fixes #2937
This adds genres to the global search dropdown (for both Books and Podcast libraries).
Since the number of results in the dropdown is limited, I also added "ORDER By numItems DESC" to the tags and genres search queries, so we return the most useful ones first.
I chose "category" from the material symbols to denote genres. Please feel free to replace this with anything else.
> Adds genres to gloabl search

- server/managers/BackupManager.js
Fixes https://github.com/advplyr/audiobookshelf/issues/2904
If the `metadata-authors/` folder does not contain a directory in it, the extraction will not create the `/metadata/authors` folder, causing a server crash and incomplete restore of the backup.
> Ensure author and items folder is created before restoring backup

- client/components/cards/ItemSearchCard.vue
- client/components/controls/GlobalSearch.vue
- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
This removes the mostly defunct matching logic from ItemSearchCard.vue, and also gets rid of the now unused matchKey and matchText fields in book and podcast search results.
> Simplify ItemSearchCard component by removing matching logic

- server/managers/AbMergeManager.js
- server/utils/ffmpegHelpers.js
- server/utils/fileUtils.js
- test/server/utils/ffmpegHelpers.test.js
This fixes #3146.
This changes the way the output of the embedding/merging tools is written back to the original directory, so that the permissions of the original audio files are kept intact. 
Before this, we used fs.move(), which moved the ffmpeg output to the original file, effectively replacing the original permissions with whatever permissions the ffmpeg process assigned to its output file. Instead, we now pipe the contents of the ffmpeg output into the original file, so the contents of the original file are replaced but all file attributes (e.g. permissions) remain intact.
> Fix permission issues in embed/merge

- client/pages/author/_id.vue
- client/pages/item/_id/index.vue
- client/pages/library/_library/podcast/download-queue.vue
- client/store/libraries.js
This fixes #3209 
The fix fixes the problem by making sure filterData is available in the store when the item page is loaded.
There might be some refactoring needed in libraries.js to make sure that dependent state variables are updated together. Currently for example, it is possible to change the currentLibraryId without trigerring a library fetch, which leaves the libraries state in an incosistent state (filterData is not updated, for example). Let me know what you think.
> On item pages, fetch the item's library data to the store if it's not available

- .github/workflows/close-issues-on-release.yml
This PR adds a workflow to automatically do the following to issues with a label of `awaiting release` whenever a release is published:
- Comment that it has been fixed with the current version number
- Close issue (if open)
- Remove `awaiting release` label
This workflow [requires write permissions for issues](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs), which is included in the workflow. The maintainer of the action I am using has not made a new release of the action since merging my PR to it, so I have just pinned the current SHA (not sure when they will get around to that).
I did not see any issues currently labeled as `awaiting release` that need to have the label removed before this workflow is ran. I tested this workflow in a personal repository and …
> Add: workflow to close issues on release

- client/pages/audiobook/_id/manage.vue
- server/managers/AbMergeManager.js
The changes allow two things:
1 - persist the advanced encoding settings so they can used as the default advanced settings
- Saves the advanced bitrate, channels, codec to local storage
- Populates the saved values if you select used advanced options
2 - Saves the advanced settings used for an encode task to the task.data so they can be shown in the in progress dialog
- Saves the passed in advanced encode options in the Task data filed
- When viewing an in progress encode task it uses these to show what the current encode is using
> persist and show the advanced encoding options

- Dockerfile
`unicode.so` is dynamically linked against glibc but Alpine only comes with musl. Installing the compatibility layer fixes it.
Fix https://github.com/advplyr/audiobookshelf/issues/3231
Fix https://github.com/advplyr/audiobookshelf/issues/3234
Close https://github.com/advplyr/audiobookshelf/pull/3235
> Fix unicode.so loading

- server/utils/fileUtils.js
This fixes #640.
UNC Paths are the standard way to refer to shared netowrk resources on Windows.
Several users have reported that these paths are not supprted in Audiobookshelf (specifically, when you specify a UNC path to a library folder, no error is generated, but scanning of that folder always fails, with weird non-existent library item paths showing up in the scan).
The reason for the bug was posix normalization. Current normalization just changes all backslashes to slashes, which is OK for most Windows paths and doesn't change path semantics. UNC paths, however, begin with a double backslash (`\\`), and when you change it to double slash (`//`), the path semantic is changed and subsequent file/path operations no longer interpret the path as a UNC path.
To fix this, I changed posix …
> Fix path normalization to support UNC paths

- client/pages/library/_library/stats.vue
This is a simple change to stop the size in bytes from splitting over two lines, causing layout issues.
> no line breaks in size text

- client/components/modals/EditSeriesInputInnerModal.vue
- client/components/ui/InputDropdown.vue
- client/components/ui/MultiSelect.vue
- client/components/ui/MultiSelectQueryInput.vue
- client/mixins/menuKeyboardNavigation.js
This fixes #3286 while refactoring the menu keyboard navigation functions into a mixin for reusability.
Aside from the refactoring, there are a couple of functional changes:
- Added menu navigation to `InputDropdown.vue` (which implements the feature request above)
- In the Add Series dialog, when the series name is accepted, the focus automatically moves to the Sequence input. This was done in order to streamline keyboard editing
- In `MultiSelect.vue` and `MultSelectQueryInput.vue`, I removed the bluring in `insertNewItem()`. This was also to streamline keyboard editing
> Refactor menu keyoboard navigation into mixin

- server/managers/BackupManager.js
- server/managers/CacheManager.js
Fixes https://github.com/advplyr/audiobookshelf/issues/3272
This PR purges the entire cache in `/metadata/cache` after restoring from a backup. The main reasoning for this is that backups may have different images or be done when migrating to a new server, so the cache should be cleared regardless.
I also updated the `CacheManager` to use `ensureDir` to be a little more readable.
> Backup restore clear cache

- server/utils/parsers/parseComicMetadata.js
This PR partially addresses some of the CBR/CBZ issues.
As mentioned in https://github.com/advplyr/audiobookshelf/issues/2750, the memory does not get freed until after the comics have completed parsing. This PR adds the `archive.close()` call at the end of the extraction functions.
I tested this by:
- Grabbing a number of random images from my personal photos
- Created a 1.8 GB CBZ and CBR comic file (no cover image, just ran the directory of images through the `zip` and `rar` bash utilities)
- Ran a scan without these changes (server crashed during scan of second book)
- Ran a scan including these changes (server completed scan of both books)
I don't have any "real" comics, so additional testing should be done on `edge` before this is part of a full release. My homemade comics did not …
> Close comics during scan

- .github/workflows/lint-openapi.yml
This PR fixes the trigger for the OpenAPI linting workflow, as well as limits the permissions for the workflow to read-only of `contents`.
> Update api linting workflow

- server/controllers/AuthorController.js
This fixes #3267 (at least partly)
Up until now, we only tested for `!author.imagePath || !(await fs.pathExists(author.imagePath))` for raw author image requests. 
The fix tests this for all author image requests.
> Update AuthorController to handle invalid image paths and log a warning

- server/managers/AbMergeManager.js
- server/managers/AudioMetadataManager.js
This fixes #3323 
The fix applies to both m4b conversion and metadata embedding when they are applied to single-file library items in the library's root folder.
> Fix embed and convert for single file library items

- server/Server.js
- server/libs/memorystore/index.js
Removes a lot of unused (in ABS) functionality, refactors to ES6 style class, and re-enables this custom implementation with check period and ttl of 1 day, and 1000 max entries.
The class now only implents the required (as per express-session docs) methods and removes optional methods, except touch() which allows the TTL of an entry to be refreshed without affecting its LRU recency.
There is no longer a way to stop the prune timer, but I don't believe the function was ever being called beforehand. The session store's lifetime is the same as the application's, and since it is unref()'d should not cause any shutdown issues.
ref: https://github.com/advplyr/audiobookshelf/issues/3251
fixes: https://github.com/advplyr/audiobookshelf/issues/2538
> memorystore: simplify, refactor, re-enable

- .github/workflows/apply_comments.yaml
This PR adds a workflow to automatically comment on issues when labels are applied to the issue. The two included with this PR are `help wanted` and `config-issue`, but they can be renamed as needed.
When an issue has the `config-issue` label applied to it, the issue will automatically be commented on using the template message and then closed as "not planned".
> Config issue workflow

- server/controllers/UserController.js
- server/models/User.js
Fixes https://github.com/advplyr/audiobookshelf/issues/3365
This PR updates the default User model to include `selectedTagsNotAccessible` on the default user creation. The `patch` request for `/api/users/{id}` is also updated to compare the payload against the default permissions to allow for values to be updated by clients on existing users which do not have the key in the `permissions` array. I'm not sure if that's the best way to do this, but figured it was more secure to validate against the default properties instead of allowing arbitrary keys to be created by a client.
This does not go through and update existing users which do not have `selectedTagsNotAccessible`.
> Fix tag permissions

- server/utils/ffmpegHelpers.js
This fixes #3379.
mp4 containers seem not to support webp images, so now they're converted to jpeg during metadata embedding.
> Convert webp images to jpeg during metadata embed

- server/scanner/Scanner.js
This fixes #3392
Fixes a couple of bugs recently introduced in [Scanner.js](https://github.com/advplyr/audiobookshelf/commit/db86bfd63d7011fdd1323d5a9c8325861f1b65b2#diff-9c1865dafeba111773e536abdf50e39124a52832acb8c5984c55ef05a2c7db4d).
> Fix crash when quick match adds new series

- server/finders/BookFinder.js
This fixes #3390.
CustomProviderAdapter.search has the potential to throw errors that weren't caught by the caller.
> Add a try-catch block around custom provider search

- package-lock.json
- package.json
- server/Database.js
- server/libs/umzug/LICENSE
- server/libs/umzug/index.js
- server/libs/umzug/storage/contract.js
- server/libs/umzug/storage/index.js
- server/libs/umzug/storage/json.js
- server/libs/umzug/storage/memory.js
- server/libs/umzug/storage/mongodb.js
- server/libs/umzug/storage/sequelize.js
- server/libs/umzug/templates.js
- server/libs/umzug/types.js
- server/libs/umzug/umzug.js
- server/managers/MigrationManager.js
- server/migrations/changelog.md
- server/migrations/readme.md
- test/server/managers/MigrationManager.test.js
- test/server/managers/migrations/v1.0.0-migration.js
- test/server/managers/migrations/v1.1.0-migration.js
- test/server/managers/migrations/v1.10.0-migration.js
- test/server/managers/migrations/v1.2.0-migration.js
- test/server/migrations/v0.0.1-migration_example.js
- test/server/migrations/v0.0.1-migration_example.test.js
This adds migration management infrastructure, based on the design and discussion [here](https://github.com/mikiher/audiobookshelf/discussions/2). 
This is for initial review - please don't merge this yet. Currently missing:
- I have not e2e-tested this yet with actual migrations (it runs, but I only ran it with an empty migrations directetory)
- I have not modified backup yet to store and restore the migrations directory.
Other than that, I think this is pretty complete. 
Please review carefully - I tried to unit test everything thoroughly, but of course I might have missed stuff.
Also, please review the readme and changlog files in `server/migrations`
> Add db migration management infratructure

- server/Logger.js
- test/server/Logger.test.js
- test/server/finders/BookFinder.test.js
This was inspired by #3398, in which the reporter attaches the log file, which doesn't contain a detailed logging of AggregateError.
Examining the Logger, I found that when logging to file and emiting log events to listeners, the log object is built like this:
```js
const logObj = {
timestamp: this.timestamp,
source: src,
message: args.join(' '),
levelName: this.getLogLevelString(level),
level
}
```
However, `Array.join` calls `toString` on each arg, which, in the case of `Error` args, just returns the name and message of the error, without the stack trace or any additional fields. 
`console.log` on the other hand, uses `util.inspect` on non-string arguments, which returns a more detailed object representation, and also has special handling for Error objects.
I fixed this issue by …
> Log non-strings into log file like console.log does

- server/managers/PlaybackSessionManager.js
- server/objects/PlaybackSession.js
If session is not sent in by the clients it defaults to 0. This uses `libraryItem.duration` when creating the session.
Duration seems like something that shouldn't have to be provided by the clients, and can safely be used from the data already present in the server. Additionally this is how it already works for the non-local sessions.
I could switch to only use it if either `!session.duration` or `session.duration !== null`, but I personally feel like there is no need to use anything other than `libraryItem` as the source of truth for this attribute in particular.
> Add duration to local sessions on creation

- server/models/Author.js
- server/models/Series.js
This PR fixes: https://github.com/advplyr/audiobookshelf/issues/2541
In summary: SQLite does not support the `LOWER`/`UPPER` function (unless it is compiled to do so, which it usually is not).
When checking if a Series/Author is already in the DB, these functions are used. Any name containing a capital non-ASCII character would always test as false and thus a new entry in the DB was created every time.
This checks is the name contains a non-ASCII character. If it does, the `lower` function is not used and the issue is avoided.
Should we not use the `lower` function at all to avoid this issue?
> Improved handling of Authors and Series with names containing non-ASCII characters

- server/scanner/LibraryScan.js
- server/scanner/LibraryScanner.js
This is in partial response to #3406
Library scan is a complex process and can fail in unexpected ways.
This tries wrap it up with a try-catch block, do the sensible things on error, save the scan log, and not crash the server.
There are a couple of questions I still have regarding the code:
- In the following code:
```js
if (canceled && !libraryScan.totalResults) {
task.setFinished('Scan canceled')
TaskManager.taskFinished(task)
const emitData = libraryScan.getScanEmitData
emitData.results = null
return
}
```
what is the last part trying to achieve? it seems it has no effect. Also, the premature return prevents some cleanups from happening.
- In the following code:
```js
if (libraryScan.totalResults) {
libraryScan.saveLog()
}
```
Why do we check library.Scan.totalResults? don't we want …
> Handle library scan failure gracefully

- client/components/modals/AccountModal.vue
- server/models/User.js
[Documentation](https://www.audiobookshelf.org/guides/users/#creating-a-new-user) specifies that new users are created without access to explicit content by default. It looks like in the recent change to the new User model, this behavior was changed. 
Personally, I think defaulting to not allowing explicit content is a safer 'fail closed' kind of mentality. Admins can manually grant explicit content access directly in ABS or through Oauth grants etc
> Default deny explicit content to users

- package.json
- server/Database.js
- server/managers/MigrationManager.js
- test/server/managers/MigrationManager.test.js
This fixes #3415 more comprehensively.
- The initial value for databaseVersion is fixed
- The isNewDatabase logic was pushed inside MigrationManager, with new tests added
- Usage of MigrationManager becomes simpler (construct, init, runMigrations unconditionally)
> Fix MigrationManager initial run behavior

- server/utils/parsers/parseComicMetadata.js
This partially fixes #3406, fixes #3399, fixes #2526 by catching file-extraction related exceptions in parseComicMetadata functions and preventing scan failure.
This is just adding straightforward try-catch block around the code.
However, there's the more general question of `libarchive`. It seems we have multiple reports of it throwing exceptions while trying to extract files from cbr/cbz files. Some observations:
- It looks like it is only used for comic file extraction on the server. 
- While libarchive throws exceptions on some cbr files, it looks like 7zip has no issues reading and extracting those files. 
- Another potential issue is that we need to read the whole archive file into memory and pass it to libarchive. This is not how modern archivers should work, and can potentially …
> Catch file extraction errors in parseComicMetadata

- client/nuxt.config.js
npm run generate had a warning related to the different format that postcss expected
edited nuxt.config.js to fix it
> added postcssOptions to remove npm warning

- server/Server.js
- server/models/PlaybackSession.js
This fixes #2662
While I'm not in the position to reproduce this (I don't own an iPhone), I'm pretty sure why the crash happens.
It is very likely due to duplicate /session/local requests (retries?) sent in rapid succession from the client and handled asynchronously on the server, causing a race condition. 
While Request A is awaiting
```js
let session = await Database.getPlaybackSession(sessionJson.id)
```
Request B is also making the same call.
both receive a null response, so each of them calls create() on the PlaybackSession model, and one of them succeeds while the other fails with UniqueConstraintError because it is trying to create a row with the same primary key.
The fix is simple - since the requests are likely identical, it is safe to use upsert instead of create, which will …
> Change PlaybackSession createFromOld to use upsert instead of create

- client/components/controls/PlaybackSpeedControl.vue
- client/components/player/PlayerPlaybackControls.vue
- client/components/player/PlayerUi.vue
This is a UI fix to adjust the playback controls so that the chapter name and play button are centered on the screen.
I moved the playback rate controls over to the right with the volume and other icons. The icons might get a little crowded on very small mobile screens (below 400px wide), but it seems okay from my testing.
This fixes #3244
> Center Play Button

- Dockerfile
- client/components/stats/DailyListeningChart.vue
- index.js
- server/Database.js
- server/controllers/LibraryItemController.js
- server/managers/BinaryManager.js
- server/utils/queries/authorFilters.js
- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
- test/server/managers/BinaryManager.test.js
This is my second attempt at integrating an SQLite extension that provides unicode aware case-folding and unaccenting, which fixes #2678 properly.
After numerous attempts and discussions with @devnoname120, I settled on [Nunicode](https://bitbucket.org/alekseyt/nunicode/src/master/) SQLite extension, which, compared to the previous ([SQlean/unicode](https://github.com/nalgeon/sqlean/blob/main/docs/unicode.md)) extension I tried:
- Does not override the SQLite NOCASE collation (which lead to crashes with the previous extension, because indices were not properly re-indexed).
- Provides superior case-folding support which wasn't provided by the previous extension (e.g. `Maße` case-folded to `masse`)
- Supports unicode-aware unaccent(), upper() and lower() functions, and a unicode aware …
> Nunicode integration

- Dockerfile
- server/managers/BinaryManager.js
Following @devnoname120's advice, I am switching to a musl-based nunicode sqlite extension on Docker, and doing away with installing and relying on gcompat (which is no longer needed). The new musl-based binaries are obtained from the new v1.2 version of nunicode-binaries.
Other nunicode binaries remain unchanged, but I switched to v1.2 in BinaryManager as well, to keep the versions consistent.
Note: BinaryManager doesn't check the exact linux version and always installs the standard glibc-based version. This means that running if you run on a non-Docker Alpine (probably as a developer), you will have to install gcomapt manually for the program to load. I think this is OK, but let me know if you want me to add a special use-case for Alpine in BinaryManager.
I tested on Docker on both …
> Use musl-based libnusqlite3 in Docker

- server/controllers/LibraryController.js
- server/models/Author.js
- server/models/Series.js
- server/utils/index.js
PR https://github.com/advplyr/audiobookshelf/pull/3414 introduced a temporary fix for issue https://github.com/advplyr/audiobookshelf/issues/2541.
Due to https://github.com/advplyr/audiobookshelf/pull/3468 the woraround became absolete and now causes the issue it fixed.
This PR retires the changes introduced in the temporary fix.
> retire unicode handling workaround for Author and Series title

- client/components/covers/AuthorImage.vue
While working on lazy loading the Author's page, I felt that we're using object-contain on author images too much - while this works nicely for covers, I feel (subjecively) that the author images look unpolished when we use object-contain. So I modified the current decision algorithm for using object-contain to only use it when the AR is very high or low.
Here's my author page before:
And after:
Some of the more significant changed are marked on the After screenshot.
I guess it's really subjective, but I find that I like the After much more, even though in some cases (e.g. John Scalzi), it results in a slightly cut image - but I think in those cases the original looks quite bad as well. 
I guess I should also work on allowing users to upload their own author image...
> Use object-cover for author images unless AR is really high or low

- client/pages/share/_slug.vue
The `Next/Prev Chapter` player buttons on the new public share page were not functioning correctly.
This fixes this issue (there's no open bug report, I think).
> Fix next/previous chapter behavior on public share player

- readme.md
Added additional parameter in the example nginx configuration that prevents 413 Request Entity Too Large error (https://github.com/advplyr/audiobookshelf/issues/825#issuecomment-1211867159)
Additionally, I changed the indentation of the config
> chore(docs): add client_max_body_size parameter in nginx config

- client/store/libraries.js
- server/utils/queries/libraryFilters.js
- server/utils/queries/libraryItemsBookFilters.js
This adds a small change to the publishedDecades filter query to allow for decades before 1000 and simplifies it a bit as well.
> Fix and simplify filter logic for publishedDecades

- client/nuxt.config.js
- client/plugins/axios.js
Your recent [Add in /dev proxy for development](https://github.com/advplyr/audiobookshelf/commit/9d1f51c6ba0201f42e72f56a3b25e539a19a8c66) is incomplete since it doesn't take care of all url references. Since the `/dev' prefix is added only for axios calls, it doesn't cover references to the server that are not through axios calls.
For this to work properly without having to modify individual references in the client code, we need to proxy all routes that need to go to the server. 
Unfortunately there's no top-level namespace (like `/server`) that identifies server paths from client paths, so we just need to specify all server paths that are referenced by the client individually.
This is what's implemented in this PR. 
- `/login`, `/logout`, `/status`, and `/init` now work properly. 
- …
> Add server proxies for all server paths

- server/utils/ffmpegHelpers.js
I've encountered the same issue as in https://github.com/advplyr/audiobookshelf/issues/2316 for files with multiple embedded covers (ex. Front and Back covers for disks)
```
2024-10-17 00:02:33.221455-07:00[2024-10-17 00:02:33.221] ERROR: [FfmpegHelpers] Extract Cover Error Error: ffmpeg exited with code 234: frame=    1 fps=0.0 q=11.2 Lq=6.8 size=N/A time=00:00:00.00 bitrate=N/A speed=   0x    
2024-10-17 00:02:33.221494-07:00Conversion failed!
```
The issue comes from the input video stream selection which is not limited to a single video stream for ffmpeg, leading to the following error:
```
[image2 @ 000001c697da0440] The specified filename 'out.jpg' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 000001c697da0440] Use a pattern such as %03d for an image …
```
> Fix "Extract Cover Error" for files with multiple embedded covers

- server/migrations/changelog.md
- server/migrations/v2.15.0-series-column-unique.js
- server/migrations/v2.15.1-reindex-nocase.js
- test/server/migrations/v2.15.0-series-column-unique.test.js
This is a migration aimed at fixing potential hidden old database index corruptiuons due to the faulty introduction of the unicode extension in v2.12.0.  It perform a reindexing of all NOCASE indices in the database.
Migration v.2.15.0 is also updated to include the same fix, since we've seen that migration fail due these corruptions.
> Add a REINDEX NOCASE v2.15.1 migration and update v2.15.0 migration

- server/migrations/changelog.md
- server/migrations/v2.15.2-index-creation.js
- server/models/BookAuthor.js
- server/models/BookSeries.js
- server/models/PodcastEpisode.js
This PR fixes https://github.com/advplyr/audiobookshelf/issues/3259, https://github.com/advplyr/audiobookshelf/issues/3525, and https://github.com/advplyr/audiobookshelf/issues/3237.
This PR adds migrations for the following indices:
- `BookAuthor` on `authorId`
- `BookSeries` on `seriesId`
- `PodcastEpisode` on `createdAt` and `podcastId` from https://github.com/advplyr/audiobookshelf/pull/3528
The author and series indexes reduce query time from multiple seconds/minutes for large databases (more than 20k items) to less than a second. I have not done much testing with large podcast databases yet. I am still investigating why some of the select book queries did not improve too much and whether this can be solved by another index.
To test the difference in query time, I did the following …
> Migration indexes

- client/players/LocalAudioPlayer.js
- client/plugins/constants.js
- server/utils/constants.js
- server/utils/globals.js
Hi there,
please add `mpeg` and `mpg` to the supported audio-types/file-extensions.
I have tons of `*.mp(e)g` podcast files in my library; which - at the moment - aren't detected by the scanner at all.
This change will fix this.
Thanks a lot!
> 'mpg' and 'mpeg' added as supported audio-type/file-extension

- client/store/globals.js
- server/Auth.js
- server/Database.js
- server/Server.js
- server/controllers/LibraryItemController.js
- server/managers/CacheManager.js
- server/models/LibraryItem.js
Following the experiments described [here](https://github.com/advplyr/audiobookshelf/discussions/3570), I made the following changes to cover image GET requests (I will do the same for author images in separate PR - wanted to focus on covers here):
- Removed authentication and user deserialization (req.user) from cover requests
- Optimized `LibraryItemController.getCover` so that no database access is made if the resized image is already in the covers disk cache
- Removed the token parameter from cover urls on the web client
This reduces the average completion time for cover requests by a factor of ~10 when acessing the server through https, and minimizes concurrent access to the database.
> Improve cover image performance

- client/components/covers/AuthorImage.vue
- server/Auth.js
- server/controllers/AuthorController.js
- server/managers/CacheManager.js
- server/routers/ApiRouter.js
This is the same as PR #3580, for author images.
> Improve author image performance

- server/Auth.js
- server/models/User.js
This PR Addresses point 5 from the [conclusions](https://github.com/advplyr/audiobookshelf/discussions/3570#discussioncomment-11119792) of the image loading performance analysis. 
An in-memory cache check and insert is introduced in all user model methods that return a single user (with their media progress) from the database. Caching this saves around 15 ms per authenticated request.
The cache doesn't have a TTL, and is invalidated only if needed (i.e. when changes to the user were not made through the cached object). I have convinced myself that all relevant writes to user and media progress are made through user model methods that are covered by a call to the `maybeInvalidate` method (and specifically in `createUpdateMediaProgressFromPayload`)
Note that this covers point 5, but I've …
> Add in-memory user cache

- .github/workflows/codeql.yml
- .github/workflows/integration-test.yml
This PR updates the triggers for the CodeQL and Integration Test actions to not include changes to the README or other unrelated files. For example, d7e810fc2f873e05eedb8ec41919656e21496412 took 4 minutes to complete actions when there was only a Readme change. The CodeQL workflow will still run every week regardless of changes.
This is a very minor thing and probably not worrying about it but something I noticed when going through action logs.
> Only run CodeQL and Integration actions if code changed

- client/pages/item/_id/index.vue
- client/pages/library/_library/podcast/download-queue.vue
- server/managers/PodcastManager.js
This fixes #3601.
The first commit removes an unnecessary socket event with a large payload that was emitted every time an episode download was queued. If a large number of episodes `n` were queued, this caused the creation of `O(n^2)` large objects to be created in quick sucession and queued for sending through the web socket, which caused an OOM for n=~2000.
The second commit resolves an unrelated bug in the podcast item page, in which if you pressed on the button to clear the download queue for a library item, the button and the message `{0} Episode(s) queued for download` were not removed after the download queue was emptied.
> Remove unnecessary episode_download_queue_updated socket event causing OOM

- server/utils/queries/libraryFilters.js
This PR adds some additional logic to the generation of `filterData` to check if any changes have occurred to the database since the data was cached to reduce the cold-start time of requesting library information. The current behavior is to cache the filter data for 30 minutes, and then clear the cache for `filterData` regardless of database state. Ideally, we will need to update the data model to generate `filterData` more efficiently, but this should account for most "normal" usage of browsing/using the server without needing large changes to the data model.
This issue is more pronounced with large libraries, such as mentioned in https://github.com/advplyr/audiobookshelf/issues/3525#issuecomment-2442787507, but is still present in smaller libraries (a cold start on my ~500 book test …
> Increase cache time for `filterdata` in library

- server/models/LibraryItem.js
This is followup to #3604.
As discussed privately, the database fetch in `LibraryItem.fullUpdateFromOld` causes a memory spike because of the query complexity. This uses a simpler query to achieve the same result.
> Use a simpler database fetch in fullUpdateFromOld

- client/components/app/MediaPlayerContainer.vue
- client/components/modals/PlayerSettingsModal.vue
- client/components/player/PlayerUi.vue
- client/pages/share/_slug.vue
I noticed that the player settings modal did not work when playing a book from the share page so I moved the player settings modal state and component to the PlayerUi component to fix this.
> Fix player settings modal on share page

- server/migrations/changelog.md
- server/migrations/v2.17.3-fk-constraints.js
- test/server/migrations/v2.17.3-fk-constraints.test.js
The migration in v2.17.0 caused the modified tables to lose their foreign key constraints. This is a [known bug](https://github.com/sequelize/sequelize/issues/12741) in sequelize.
This resolves server crashes when deleting records in the affected table that have an association. 
This migration does the following for each table affected (follows the outlined method in [sqlite docs](https://www.sqlite.org/lang_altertable.html#otheralter)):
1. Creates a new table with a temp name with the correct fk constraints
2. Populates the new table with the original tables records
3. Drops the old table
4. Renames the old table to the original
Testing in progress.
Will most likely add an additional check to see if this migration is necessary for users who have downgraded and are upgrading again.
> Add migration to fix dropped foreign key constraints dropped in v2.17.0 migration

- server/controllers/LibraryController.js
- server/controllers/LibraryItemController.js
- server/managers/CacheManager.js
- server/objects/LibraryItem.js
- server/routers/ApiRouter.js
- test/server/controllers/LibraryItemController.test.js
See https://github.com/advplyr/audiobookshelf/issues/3668 for the outlined issue
Fixes #3668 
Anytime a book is removed/updated we need to ensure that authors with no books (and metadata) and empty series get cleaned up.
This PR adds 2 functions that take in an array of seriesIds and authorIds. Those series & authors are checked for removal.
Working on unit test.
> Fix:Remove authors with no books when a books is removed #3668

- server/utils/queries/userStats.js
This PR introduces optional operators to allow stats to function without media metadata for playback Sessions. This change prevents server crashes when media metadata is absent.
The logic for handling authors, narrators, genres has been updated to handle cases where `mediaMetadata` is absent. This ensures that the server can generate responses without requiring metadata, thereby preventing crashes.
A follow-up PR should be made to pull the `mediaMetadata` when missing from request.
Tested on a personal server.
> Resolved a server crash when a playback session lacked media metadata

- client/components/modals/rssfeed/OpenCloseModal.vue
- client/components/modals/rssfeed/ViewFeedModal.vue
- client/pages/config/rss-feeds.vue
- server/Server.js
- server/managers/RssFeedManager.js
- server/migrations/changelog.md
- server/migrations/v2.17.5-remove-host-from-feed-urls.js
- server/objects/Feed.js
- server/objects/FeedEpisode.js
- server/objects/FeedMeta.js
- test/server/migrations/v2.17.5-remove-host-from-feed-urls.test.js
This fixes #3563, and also makes the necessary preparation for subdirectory support for RSS feeds.
Fixes #3563
This removes the protocol and host from all URLs in the Feeds and FeedEpisodes tables (including a migration that changes existing records). The host and protocol are now dynamically determined at runtime based on the request.
The web client is also modified to handle the shortened URLs.
This achieves 2 goals:
1. It fixes the issues described in #3563
2. It enables subdirectory support by properly accounting for the subdirectory in generated URLs.
The migration (both up and down) has been unit tested and also tested against a real ABS database.
Modifications to server and client were tested with both existing (non-subdirectory) and subdirectory builds. The server and client were …
> Remove serverAddress from Feeds and FeedEpisodes URLs

- server/controllers/RSSFeedController.js
- server/managers/RssFeedManager.js
- server/models/Book.js
- server/models/Feed.js
- server/models/FeedEpisode.js
- server/models/LibraryItem.js
- server/objects/Feed.js
Begin migrating `Feed` and `FeedEpisode` to use the new model.
This PR updates the create feed for library item logic to use the new models in `/models` folder instead of the old models in the `/objects` folder.
The objective for the migration is to eventually remove the old models. In the meantime the API will return the same data so the new models will implement `toOldJSON` functions when necessary.
For the first step of the migration, creating feeds from library items is handled in the new `Feed` and `FeedEpisode` models.
This also adds necessary helper functions in the `LibraryItem` and `Book` models.
Tested opening feeds for both audiobooks and podcasts. Tested opening feeds with options (prevent indexing, owner name, owner email).
> Refactor Feed model to create new feed for library item

- client/components/stats/YearInReview.vue
- client/components/stats/YearInReviewBanner.vue
- client/components/stats/YearInReviewServer.vue
- client/components/ui/Dropdown.vue
Adds a dropdown to select the year to view in Year in Review.
Discord request
This adds a dropdown displaying the years from the user's creation year up to the current year. The default year remains unchanged. It allows users to view both past years and the current year. Some of the displayed data is quite interesting, making it a valuable option to explore even before the year ends.
The button is shown only when there is more than one year. Additionally, I included a prop in the dropdown to enable adding custom classes to the dropdown button.
Devserver with production database
> DropDown for Year in Review

- client/plugins/i18n.js
Added Australia and New Zealand podcast store regions
Added AU/NZ podcast store regions
Pretty self explanatory
> feat: Added Australia and New Zealand podcast regions

- server/utils/zipHelpers.js
This PR speeds up the endpoint for downloading the zip of a library item by removing compression.
Partially fixes https://github.com/advplyr/audiobookshelf/issues/3081
Removing compression on downloads for library items greatly reduces CPU usage (removes costly compression, just streams directly from file to response). This does increase file size by about 2-3%, but removes the limit of 10-15 MBps (depending on hardware) for downloading a zip file. Compressing already compressed files does not really save any bandwidth. More discussion in https://github.com/advplyr/audiobookshelf/issues/3081#issuecomment-2526359501
This can increase download time if the network connection is slower than 10 MBps by about 2-3% due to the file size being slightly larger.
I did investigate adding the …
> Change: no compression when downloading library item as zip file

- client/pages/config/rss-feeds.vue
This PR forces the height of the image preview in the RSS feed to be square and match the size of the width.
This should fix https://github.com/advplyr/audiobookshelf/issues/3748
This PR replaces the `h-full` with `h-auto`. I did play with changing this to be a `div` to force the images to be square, but the current behavior allows for rectangular aspect ratios so I stuck with `h-auto`.
The `h-full` attribute only seems to be an issue in Safari, as per #3748.
Tested with square and rectangular covers. Tested with series and individual books.
Only tested in Firefox, because I do not have access to a Mac for testing on Safari.
> Change: height of RSS feed preview to match aspect ratio

- client/components/app/MediaPlayerContainer.vue
- client/pages/share/_slug.vue
Adds Media Session API to Share audio player to match the regular audio player.
Support the `chapterInfo` array for media sessions.
Fixes #3768
I noticed the experimental [ChapterInformation](https://developer.mozilla.org/en-US/docs/Web/API/ChapterInformation) interface that allows for passing in chapters to the media session.
I wasn't able to test this since it looks like it is only being used ChromeOS media notifications based on this article: https://web.dev/articles/media-session
Tested this in Brave, Firefox and Edge on Windows.
> Use Media Session API in the Share audio player & pass chapterInfo to media sessions

- server/migrations/changelog.md
- server/migrations/v2.17.7-add-indices.js
- server/models/Book.js
- server/models/LibraryItem.js
This adds indices to significantly improve database library query time when sorting by size or duration.
There's no issue. I encountered this while working on PR #3726.
The following query in `libraryItemsBookFilters.js` is where most of books fetch time is spent and its performance heavily depends on `sortOrder`. When fast scrolling on the library page happens, this can lead to choking on the server if a number of page requests are handled concurrently.
```js
const { rows: books, count } = await Database.bookModel.findAndCountAll({
where: bookWhere,
distinct: true,
attributes: bookAttributes,
replacements,
include: [
{
model: Database.libraryItemModel,
required: true,
where: libraryItemWhere,
include: libraryItemIncludes
},
seriesInclude,
authorInclude,
...bookIncludes
],
order: …
```
> Book query optimizations

- server/managers/RssFeedManager.js
- server/models/Feed.js
- server/models/FeedEpisode.js
Feed episodes were dropping and re-creating the table record anytime a feed needed to be updated. Since the generated RSS feed uses the content url as the GUID this was changing on every update causing podcast clients to think it is a new episode.
https://github.com/advplyr/audiobookshelf/issues/3757
To fix this the existing `FeedEpisode` records are loaded and the `filePath` is compared to see if a `FeedEpisode` should be updated. So if the filepath changes then the generated RSS feed guid will change.
Another option could be using the inode value but this would require storing the inode value in the `FeedEpisode` model and would cause issues for users using a file system that doesn't support unique inode values.
This fixes 3 other issues that I found while testing.
1. For audiobook …
> Feed episode IDs changing on refresh & several other refresh issues

- server/Server.js
Make downloading podcast episodes work when `HTTP_PROXY`/`HTTPS_PROXY` environment variable are present.
#1313 
Mannually following redirects seems to fix the bug in axios when using a proxy. It is merely a workaround while we wait to upgrade axios / replace pkg like mentionned [here](https://github.com/advplyr/audiobookshelf/pull/2666#issuecomment-1974083316).
Ran a forward proxy locally using docker, and added both `HTTP_PROXY` and `HTTPS_PROXY` to the start command. Then, I searched and downloaded a few podcast episodes.
> Experimental proxy support by manually following redirects

- server/Database.js
- server/controllers/LibraryItemController.js
- server/models/Playlist.js
- server/routers/ApiRouter.js
Deleting an audio file for a podcast episode from the library files table will remove the associated podcast episode.
When removing an episode in that way the playlist media item was not getting removed.
This caused a crash when querying for that playlist.
Fixes https://github.com/advplyr/audiobookshelf/issues/3784
To solve the crash the `cleanDatabase` startup function will remove any `playlistMediaItem` records with no associated media item.
In fixing the underlying issue I also added a missing check to remove `mediaProgress` records for that episode.
Tested with both podcast and book playlists deleting the episode/book both from the UI and manually from the database.
> Fix remove episode from playlist

- server/controllers/PodcastController.js
- server/managers/CoverManager.js
- server/managers/CronManager.js
- server/managers/NotificationManager.js
- server/managers/PodcastManager.js
- server/models/Podcast.js
- server/models/PodcastEpisode.js
- server/objects/LibraryItem.js
- server/objects/PodcastEpisodeDownload.js
- server/objects/entities/PodcastEpisode.js
- server/objects/mediaTypes/Podcast.js
- server/objects/metadata/PodcastMetadata.js
- server/utils/ffmpegHelpers.js
- server/utils/podcastUtils.js
Continuation of https://github.com/advplyr/audiobookshelf/pull/3779
Handles PodcastManager and creating podcasts
> Update podcasts to new library item model

- server/Database.js
- server/controllers/AuthorController.js
- server/controllers/CollectionController.js
- server/controllers/EmailController.js
- server/controllers/LibraryController.js
- server/controllers/LibraryItemController.js
- server/controllers/MeController.js
- server/controllers/MiscController.js
- server/controllers/PlaylistController.js
- server/managers/PlaybackSessionManager.js
- server/managers/PodcastManager.js
- server/models/Collection.js
- server/models/LibraryItem.js
- server/models/Playlist.js
- server/objects/LibraryItem.js
- server/objects/mediaTypes/Podcast.js
- server/scanner/LibraryItemScanner.js
- server/scanner/LibraryScanner.js
- server/utils/migrations/dbMigration.js
- server/utils/queries/libraryFilters.js
- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
- server/utils/queries/seriesFilters.js
Continuation of https://github.com/advplyr/audiobookshelf/pull/3779
> Migrate controllers to use new toOldJSON functions

- server/objects/Stream.js
Fixes wrong usage of `ffmpeg.addOption` in `Stream.js`.
Fixes #3793
See [my comment](https://github.com/advplyr/audiobookshelf/issues/3793#issuecomment-2571368333) on the bug.
Used a metadata directory with spaces in it. 
Played a book that requires transcoding in iOS/Safari.
This previously failed and now it plays correctly.
> Fix ffmpeg.addOption for transcoding

- server/managers/ApiCacheManager.js
- server/routers/ApiRouter.js
Fix case-sensitive matching for API Cache Manager.
CodeQL issue from PR #3335.
Workflow output: https://github.com/advplyr/audiobookshelf/pull/3335/checks?check_run_id=35084757148
https://github.com/advplyr/audiobookshelf/pull/3335#issuecomment-2567188052
This PR changes the regex path matching to be case insensitive for the API Cache Manager. Two methods I found were to force all request URLs to be lowercase, or to ensure that the regex matches against a case-insensitive string. I chose to use case-insensitive matching for now due to some routes potentially being case sensitive, such as:
`DELETE /api/tags/:tag`
`DELETE /api/genres/:genre`
I changed various API calls in the web client to use various capitalization for library API endpoints and verified that everything was still routed …
> API Cache Manager route uses case-insensitive match

- server/utils/ffmpegHelpers.js
This fixes an escaping issue causing UNC paths not to be read correctly in ffmpeg concat files generated by ABS
Fixes the re-opened [audiobookshelf-windows issue #29](https://github.com/mikiher/audiobookshelf-windows/issues/29#issuecomment-2547238819).
The issue was that the \\\\ chatacters in the beginning of the UNC path were not escaped in the ffmpeg concat file, and therefore the path was mangled. 
Rather than escaping those, I fixed this by surrounding file paths in the concat file with single quotes (and consequently also modifying `escapeSingleQuotes`)
This way is safer, since now the only character that needs escaping inside a file name is a single quote, which the aptly named `escapeSingleQuotes` function now really does - no other characters (like spaces or backslashes) need to …
> Fix ffmpeg concat file escaping

- client/components/ui/VueTrix.vue
This fixes a couple of issues with the Trix text editor
- Trix translates `p` tags to `div` by default, and inserts redundant `br` tags on paragraph breaks. This fixes this.
- Trix by default always puts a `br` tag on Enter, and never breaks a paragraph (there's literally no way to start a new paragraph). This changes the behavior to break paragraphs on Enter (you can still use Shfit+Enter for line breaks, like in other normal editors)
This was tested on various podcast episode descriptions in the Episode Details tab.
> Fix Trix to use paragraphs and break on return

- readme.md
Changes our recommendation for Nginx reverse proxy setup to set the `Host` header to `$http_host` instead of `$host`
This helped in fixing #3809, which turned out to be caused by Ngnix misconfiguration.
In Ngnix, `$host` and `$http_host` are usually the same, except when Nginx is configured to a non-standard HTTP port (i.e. not 80 or 443). When Nginx uses a non-standard HTTP port, `$host` is just the hostname without the port, while `$http_host` is the actual 
`Host` header from the original request, which has both hostname and port.
Since ABS now uses the host to construct RSS feed entries dynamically, it's important to get the actual host from the original request, so that feed links are properly constructed.
Changing the config solved the issue for #3809 reporter.
> recommend using $http_host for ngnix

- client/components/tables/podcast/LazyEpisodesTable.vue
- server/controllers/PodcastController.js
This fixes a couple of issues in LazyEpisodeTable:
- When an episode is updated, the refresh doesn't account for the current scroll position
- When an episode is removed, it is not reflected in the table (a zombie episode remains)
There is no open issue for these (came up over discord discussion).
There were two bugs fixed:
- On the client, when a podcast episode is updated, the `LazyEpisodeTable.refresh()` was called, but it always mounted the first few episodes in the table, with no regard for the current scroll position.
- On the server, when a podcast episode was removed, the episode was not removed from the libraryItem object return to the client, so a zombie episode was shown after the update.
Updated, added and removed podcast episodes.
> Episode table refresh fixes

- client/cypress/tests/utils/ElapsedPrettyExtended.cy.js
- client/plugins/utils.js
Correct rounding and carry of minutes in client/plugins/utils.js:: Vue.prototype.$elapsedPrettyExtended
-Add cypress tests for Vue.prototype.$elapsedPrettyExtended function
Note: This is my first PR to the project, any feedback would be appreciated.
In the Audiobookshelf Year In Review, there was a time at which the App reported
"Listening Time" as "44d23h60m", but it should have been "Listening Time" as "45d"
| Correct Display | Bug Display |
|:---------------:|:-----------:|
| <img src="https://github.com/user-attachments/assets/a883099f-5439-4f40-b3c2-3719241df498" width="200" alt="Year In Review OK"> | <img src="https://github.com/user-attachments/assets/bfa344a3-786d-4366-9eb0-0ccd88a274c7" width="200" alt="Year In Review BUG"> |
Fixes #3817
In client/plugins/utils.js:: …
> Fixes #3817 Correct rounding and carry of minutes in client/plugins/utils.js::$elapsedPrettyExtended

- client/components/tables/podcast/LazyEpisodesTable.vue
Instead of using a fixed size for episodeRowHeight, it is given a default value but recalculated when the episode table is mounted.
This fixes #3511. While this is marked as related to #3013, I believe they're not actually related.
The bug was reproduced by manually setting the root font-size to a larger value (I suspected that this might be reason, because the reporter mentioned system scale changes).
The original code hardcodes episodeRowHeight value to 176 px (which is indeed the row height when the root font size is the default 16px). episodeRowHeight is used to make scroll calculations to decide which episodes to mount, and when it is different from the actual value, it results in mounting incorrect episodes.
The fix determines episodeRowHeight from the actual dom element of the …
> Dynamically calculate episode row height on LazyEpisodeTable init

- client/nuxt.config.js
- index.js
- prod.js
Switch to enabling subdirectory support with `/audiobookshelf` on the server and web client, according to the plan laid out in discussion #3535.
This finally fixes #385
Users will now be able to set their reverse proxies to proxy `/audiobookshelf` subdirectory requests
This is the last step in supporting subdirectory with the existing static site generation approach. 
The plan is described in detail in #3535.
As a reminder, this will set a fixed subdirectory of `/audiobookshelf` on the web client (non-subdirectory paths will get rewritten by the server), and the server will support both subdirectory requests (with `/audiobookshelf` prefix) and non-subdirectory requests (with no prefix).
_Note_: Mobile app support for subdirectory is already implemented and checked in with …
> Enable subdirectory support by default

- client/assets/app.css
- client/components/readers/EpubReader.vue
Fixes a missing texture image in the nuxt build.
This addresses [this comment](https://github.com/advplyr/audiobookshelf/issues/385#issuecomment-2601167818) in #385
Fixes #3865
`assets/app.css` contained a direct url link to `/textures/wood_default.jpg`. This breaks subdirectory support. Changed this to `~static/textures/wood_default.jpg` so it is picked and served by _nuxt (like other urls in the .css files)
Ran against a dev server. The texture image is now fetched successfully from `/audiobookshelf/_nuxt/img/wood_default.6d366e7.jpg` instead of  `/textures/wood_default.jpg`.
> Fix missing texture image & epub ebook url for subdirectory support

- server/models/Feed.js
- server/models/FeedEpisode.js
- server/utils/index.js
A few adjustments to fix/improve the generated RSS feed.
Series & collection feeds were broken due to the `getTrackList` request returning an empty array.
Fixes #3866
Although these are likely not the actual issue the user is having in that issue it points to some things this PR addresses.
The following updates were made:
1. Feeds no longer include empty tags. For example, previously an empty season would include `<itunes:season/>`.
2. `itunes:summary` value is wrapped in `<![CDATA[ .... ]]>` because podcast episode descriptions include HTML
3. `itunes:description` value is an integer of seconds
4. Removed unnecessary podlove namespace
5. Fixes an issue with series and collection feeds where the episode list is empty
Tested opening feeds of all variety
> Updates to generated RSS feed & Fix series/collection feeds

- readme.md
Updates README and gives an example on how to make websockets work using Apache as a reverse proxy.
#3810  - updating README
After PR #3810, one [comment](https://github.com/advplyr/audiobookshelf/pull/3810#issuecomment-2605357722) proposes to update the README to say `RewriteRule (.*)/audiobookshelf/?(.*) "ws://127.0.0.1:<audiobookshelf_port>/audiobookshelf/$2" [P,L]`. However, this did not work for me.
Also, it looks like [other users](https://github.com/advplyr/audiobookshelf/issues/3868) are seeing issues with setting up web sockets too using the latest version, but it is not clear if the proposal above was tried.
On Apache 2.4.62, with the following configuration:
<Location /audiobookshelf>
ProxyPreserveHost on
ProxyPass http://${my_docker_host}:80/audiobookshelf upgrade=websocket …
> Update README on using websockets with Apache as a reverse proxy

- client/assets/defaultStyles.css
- client/assets/trix.css
- client/components/cards/BookMatchCard.vue
- client/components/modals/item/tabs/Match.vue
- client/components/modals/podcast/ViewEpisode.vue
- client/components/ui/RichTextEditor.vue
- client/components/ui/VueTrix.vue
- client/components/widgets/BookDetailsEdit.vue
- client/pages/item/_id/index.vue
- server/finders/BookFinder.js
- server/models/Book.js
- server/providers/Audible.js
- server/providers/iTunes.js
- server/utils/htmlSanitizer.js
Add support for rich text in book descriptions (including matching and editing).
Fixes #1820, #3786
This adds the following:
- Centralized sanitization of match results.
- Rich text editing for book descriptions (including match results)
- Proper display of rich text book descriptions in item pages
The following changes were made:
- `BookDetailsEdit.vue` and `Match.vue`
- Replaced `text-area-with-label` with `rich-text-editor` for the description field.
- `RichTextEditor.vue`
- Added `style="margin-top: 0; margin-bottom: 0.125em"` to the label. This was to make it more compatible with `TextareaWithLabel`.
- Added `blur` method to the editor. This is required by `Details.vue`.
- Remvoed the `config` prop. It was moved into `VueTrix`.
- `VueTrix.vue`
- Put the trix-toolbar into the …
> Support rich text book descriptions

- server/models/LibraryItem.js
Adds `bookSeries.id` attribute to the sequelize query in `LibraryItem.findAllExpandedWhere`.
Fixes #3883
The bookSeries id is required for the `bookSeries.destroy()` call [here](https://github.com/advplyr/audiobookshelf/blob/e096da1b4d0dfeab02f7a6702cf56237e12e04e8/server/scanner/Scanner.js#L338), without it, the `destory()` call throws an exception since it doesn't have the id in order to construct the deletion query.
_Note_: this only happens in batch quick match, which calls `findAllExpandedWhere()`
Batch quick match which crashed the server before now completes successfuly.
> Add bookSeries id attribute to findAllExpandedWhere

- server/Database.js
Adds support for setting some whitelisted SQLite PRAGMA values through environment variables.
Fixes #3750
A whitelist of allowed pragma settings is defined,  which currently contains `mmap_size`, `cache_size`, and `temp_store`.
Users can set the values for those pragmas, by setting the environment variable `SQLITE_<UPPERCASE_PRAGMA_NAME>` (e.g. SQLITE_MMAP_SIZE) to the requested value.
These helped the reporting user optimize their database, and could be used by us in the future to set reasonable default values.
Set up all the supported pragmas through the corresponding env variables.
> Allows setting of some pragma values through environment variables

- server/objects/PodcastEpisodeDownload.js
when two podcast's episode advertise the same filename, a random ID will get added to ensure that theses do not overlap.
sadly, the generation of this random ID is redone everytime `PodcastEpisodeDownload.targetFilename` is accessed and so the filename is changing, making ffmpeg outputting to a different path than excepted.
there is already an `id` field in this class, which is, as far as my IDE told me, not used for anything else. it was probably meant to be used for that exact purpose.
I actually found the issue when investigating why [this podcast](https://podcasts.apple.com/ch/podcast/id311604979) wasn't updating anymore. I tried to download two episodes with the same name and it failed with
```
DEBUG [FfmpegHelpers] downloadPodcastEpisode: Cmd: ffmpeg -i pipe:0 -y -loglevel debug …
```
> server/podcast: stabilize random ID

- .github/workflows/close_blank_issues.yaml
Adds a workflow to close issues which do not use the issue templates
No issue number
To help encourage users to use the issue templates, this workflow closes any issues which are opened and have less than 3 headings in them. This does not prevent users from opening issues with their own headings, but should help prevent the blank issue template from being used.
Tested with my issue templates repo
> Add: workflow to close blank issues

- client/assets/app.css
- client/components/cards/LazyBookCard.vue
- client/components/cards/LazySeriesCard.vue
Adds box shadow to progress bar on cover for both library items and series.
The change is subtle and can be improved on further in the future.
This also updates the progress bar to be above the overlay on hover.
Fixes #3825
Before
After
On hover:
> Adds box shadow to progress bar on covers for visibility #3825

- server/Logger.js
`Logger.fatal` is called before the server closes on uncaught exceptions. When it gets called the log is written to `crash_logs.txt`.
Logs weren't always being written to crash_logs.txt because `Logger.fatal` wasn't a promise and `process.exit` was called before it was done.
No issue
Threw some exceptions and ensured they were written to crash_logs.txt
> Fix Logger.fatal to ensure crash_logs.txt is written to

- client/pages/audiobook/_id/chapters.vue
- client/players/AudioTrack.js
- client/players/PlayerHandler.js
- server/models/Book.js
- server/models/PodcastEpisode.js
- server/objects/files/AudioTrack.js
API endpoints that return expanded Books and PodcastEpisodes include AudioTrack objects that have a `contentUrl`. That `contentUrl` was incorrectly including the basepath (/audiobookshelf). This PR removes the basepath from the API responses and prepends the basepath in the web client.
No issue
The mobile clients and 3rd party clients will be getting users server address and prepending it to the `contentUrl` returned from the API.
If the `contentUrl` includes the basepath and the user includes the basepath in the address then it will result in track urls with `/audiobookshelf/audiobookshelf/`.
The mobile apps are currently falling back to transcoding if the user includes the basepath. This PR fixes that issue with no additional changes on the mobile apps.
Tested streaming on web client …
> Fix API including basepath in tracks contentUrl

- client/components/ui/VueTrix.vue
Adds a resize handle to the rich text editor.
Fixes #3928 
- Added `resize: vertical` to text-editor style
- Set `height` and `min-height` properties (instead of `max-height`)
Resize handle now shows up where the rich text editor appears, and works as expected.
> Add resize to trix editor

- server/utils/podcastUtils.js
This commit adds the `Accept-Encoding` header to `getPodcastFeed()` with gzip, compress, and deflate support. This allows servers to send a compressed response that'll be decompressed by axios transparently.
Fixes #3885 
Audiobookshelf is currently using axios v0.27.2, which [enables the `decompress` option by default](https://github.com/axios/axios/blob/v0.27.2/README.md?plain=1#L475). The `decompress` feature supports gzip, compress, and deflate algorithms (see [axios/lib/adapters/http.js](https://github.com/axios/axios/blob/v0.27.2/lib/adapters/http.js#L272)). axios v0.27.2 does not add the `Accept-Encoding` header to requests automatically, so that's the responsibility of the caller.
I applied the change to my production Audiobookshelf container and was then able to fetch the …
> Add `Accept-Encoding` header to `getPodcastFeed()`

- client/components/modals/podcast/tabs/EpisodeDetails.vue
- client/components/ui/MultiSelectQueryInput.vue
- client/components/ui/TextInput.vue
- client/components/ui/TextInputWithLabel.vue
- client/components/widgets/BookDetailsEdit.vue
- client/components/widgets/PodcastDetailsEdit.vue
- client/pages/batch/index.vue
Adds `trimWhitespace` prop to TextInput component to trim whitespace from text inputs on blur.
Fixes MultiSelectQueryInput that was allowing empty authors & trims
Fixes #3943
> Trim whitespace from podcast/book/episode & batch edit text inputs

- client/components/app/BookShelfRow.vue
- client/components/modals/item/EditModal.vue
- client/components/modals/podcast/EditEpisode.vue
- client/components/widgets/ItemSlider.vue
This fixes 2 issues.
1. #3951 
2. Next/prev buttons are showing when editing episodes on the home page when they shouldn't be (reproducible steps below)
Fixes #3951
To reproduce 2 above:
1. Navigate to a podcast page that has multiple episodes
2. Press edit for a episode and notice the next/prev buttons work correctly.
3. Close the modal and navigate to the home page.
4. Press edit on an episode card and notice the next/prev buttons show but when pressed throw an error.
The reason is because the episodes from the podcast page are not being cleared and the home page doesn't support the next/prev buttons.
> Fix next/prev buttons on edit modals not changing description when focused

- client/nuxt.config.js
- index.js
- prod.js
When the `ROUTER_BASE_PATH` env variable is set to an empty string it's mistakenly overriden to `/audiobookshelf` instead.
The `/audiobookshelf` fallback should only be used when the `ROUTER_BASE_PATH` env variable is undefined, not just an empty string.
Regression introduced in https://github.com/advplyr/audiobookshelf/pull/3810
See also: https://github.com/advplyr/audiobookshelf/pull/3810#discussion_r1948790937
Related: https://github.com/advplyr/audiobookshelf/issues/3874 (requires frontend recompilation to fix that one)
Running the following before starting Audiobookshelf:
```shell
export ROUTER_BASE_PATH=''
```
N/A
> Fix `ROUTER_BASE_PATH` override for empty string

- server/migrations/changelog.md
- server/migrations/v2.19.1-copy-title-to-library-items.js
- server/models/Book.js
- server/models/LibraryItem.js
- server/scanner/BookScanner.js
- server/utils/profiler.js
- server/utils/queries/libraryItemsBookFilters.js
- test/server/migrations/v2.19.1-copy-title-to-library-items.test.js
Significantly improves book library Sequelize page queries for the following sort orders:
- title (with or without ignorePrefix)
- addedAt
This partially fixes #2073 (resolving the book library load times, but not the podcast library load times)
After digging more into the details of the issues people were complaining about in #2073 and doing additional performance analysis in Sequelize query to bring the page [here](https://github.com/advplyr/audiobookshelf/blob/25ae6dd59a06f9f6f62c97d98ead908b23d5bc37/server/utils/queries/libraryItemsBookFilters.js#L563), I made the following observations:
1. Due the the current architecture of the database (specifically, the separate libraryItems and books tables), SQLite cannot sort the results of the main query efficiently, even when an index on the …
> Improve book library page query performance on title, titleIgnorePrefix, and addedAt sort orders.

- server/Auth.js
This fixes the security issue noted in the advisory below:
- it matches against anchored patterns
- it tests `req.path` against the patterns (instead of `req.originalUrl`)
https://github.com/advplyr/audiobookshelf/security/advisories/GHSA-pg8v-5jcv-wrvw
Because we are now testing `req.path` against anchored patterns, the pattens needed to be changed a bit, since this code (which is called from the `ifAuthNeeded` middleware is used in two separate locations:
- at the app level, where `req.path` begins with `${global.RouterBasePath}/api`
- at the API router level, where `req.path` is already stripped of `${global.RouterBasePath}/api`
So the patterns need to change to:
```js
new RegExp(`^(${escapedRouterBasePath}/api)?/items/[^/]+/cover$`), 
new …
```
> Security fix for GHSA-pg8v-5jcv-wrvw

- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
Fixes server crash when making certain queries with title/titleIgnorePrefix
Fixes #3966
When making custom queries in Sequelize we need to include the table name along with the column name to prevent issues of column ambiguity.
There are 3 cases I found where this happens.
1. Searching in the library controller search endpoint
2. Library items query for book libraries when sorting ignore prefix is enabled
3. Library items query when collapse series is enabled and sorting ignore prefix is enabled
> Fix server crash remove column name ambiguity #3966

- server/utils/queries/libraryItemsBookFilters.js
- server/utils/stringifySequelizeQuery.js
Book library queries are returning the incorrect count because the cached key is matching when it shouldn't. 
Sequelizes uses Symbols in the queries and JSON.stringify ignores these. This adds a separate function that sanitizes the query before Stringify.
Fixes #3979
Reproduce by filtering by Issues and clearing the filter. Those 2 cache keys will be the same because the library item where option is not stringified.
> Fix count cache by stringify Symbols #3979

- client/components/app/MediaPlayerContainer.vue
End of chapter sleep timer implemented in #2059 has an issue where the chapter can switch between function calls to `checkChapterEnd`.
It is easiest to test this bug by increasing the playback speed
Fixes #3969
This is solved by storing the last chapter id and comparing the current chapter with the last. If they changed then stop the timer.
The difference from the previous implementation will be that if you change chapters while the EoC sleep timer is activated then it will end the sleep timer. I think that is normal
> Fix chapter end sleep timer sometimes not stopping #3969

- server/models/LibraryItem.js
- server/scanner/Scanner.js
When using the library option quick match all the server will crash if it detects an existing series sequence needs to be updated.
Fixes #3961
To reproduce this:
1. Find a book that quick matches with a series and sequence.
2. Change the series sequence number
3. Trigger quick match all in the more menu dropdown of the library
The issue is when querying for the library items the `id` of the `bookSeries` isn't being pulled.
> Fix server crash when quick match all updates series sequence #3961

- server/utils/podcastUtils.js
Allow adding podcasts where the server detects an `http` domain and redirects to an `https` domain. Currently, these fail with an error message that is not useful to the end user.
Fixes #3142  
Fixes #3658  
This error occurs for several mainstream podcasts, likely impacting multiple users. I lost some spouse approval points due to this issue. 😅
The root cause is that we are not allowing the Axios client to redirect between domains with different protocols. As a result, any feed URL detected as `http` that redirects to a different `https` domain would fail, leaving users without a clear resolution.  
- When a podcast feed request fails due to a redirection error caused by an invalid protocol, we check if the redirection is **from `http` to `https`**.
- If so, we upgrade the **original** …
> fix: allow upgrading HTTP to HTTPS for redirects

- client/components/app/LazyBookshelf.vue
When a bookshelf is sorted by title and the title of a book/podcast changes (e.g. after being edited), the bookshelf is rebuilt so the book appears at its proper position (based on its new title)
Fixes #3998
Up until now, when `LazyBookshelf` got an `item_updated` message from the server, it only replaced the old entity with the updated entity. With this change, if the current sort order is by title, and a change of title is detected, `resetEntities()` is called, and the item is moved to its new position.
Changed title of books/podcasts and verified that after saving the change, the book/podcast moved to its new position.
> Re-sort title-sorted bookshelf after title change

- client/components/app/MediaPlayerContainer.vue
Prevent long author strings from pushing the player controls down by truncating the text.
There's no issue number. I just noticed this and thought it could be cleaned up.
I added the truncate class to the `div` containing the author information.
I've tested the change in the browser to make sure it makes the player controls look better.
Before:
After:
> prevent long author strings from pushing the player controls down by truncating

- server/controllers/LibraryController.js
This PR addresses a security vulnerability in the LibraryController by enforcing admin-level authorization for critical endpoints that were previously accessible to non-admin users. Specifically, it restricts access to library settings updates, library issue removal, and **library deletion** to only admin users.
No issue reported (security fix).
This PR implements admin-level authorization checks in the `LibraryController` for the following methods:
*   **`PATCH /api/libraries/:id` (update method):**  Previously, any authenticated user could potentially modify library settings. This change adds a check at the beginning of the `update` method to ensure that only users with `isAdminOrUp` privileges can proceed with updating library settings.
*   **`DELETE /api/libraries/:id/issues` …
> fix(auth): Add admin-level auth to LibraryController 'delete', 'update' and 'delete items with issues'

- server/Watcher.js
- server/utils/fileUtils.js
- test/server/utils/fileUtils.test.js
This PR refactors the "file ignore" for the scanner and watcher.
Fixes https://github.com/advplyr/audiobookshelf/issues/2399 and https://github.com/advplyr/audiobookshelf/issues/4029
This helps with https://github.com/advplyr/audiobookshelf/issues/1641, but is not user-configurable like that request is.
This adds additional file extensions to the ignore list in the scanner and watcher, and creates a new utility function to ensure both ignore lists stay in sync.
Ignored file extensions are:
- `.part`
- `.tmp`
- `.temp`
- `.crdownload`
- `.download`
- `.bak`
- `.old`
- `.tempfile`
- `.tempfile~`
This function also checks for dotfiles and dotpaths to simplify the calling functions.
This function adds a framework to ignore the file or path whenever a specific string appears anywhere in the …
> Refactor ignore file logic

- server/providers/CustomProviderAdapter.js
This PR adds logging for the Custom Metadata Provider URL request to match other providers.
Additional logging for https://github.com/advplyr/audiobookshelf/issues/4004
Moved URL creation with query string to be before the Axios request and added logging of the generated URL.
Verified not crashing
N/A
> Add: log custom metadata provider to match other providers

- client/components/tables/podcast/LazyEpisodesTable.vue
- client/pages/item/_id/index.vue
- client/store/index.js
This PR changes the "Play" button on the podcast page to play the first incomplete episode in the table instead of the "newest published". The "first episode" is the top row, and is dependent on the sorting and filtering options.
Related to https://github.com/advplyr/audiobookshelf/issues/1321.
This PR adds a new field to the Vuex store to track the podcast episode IDs in the `LazyEpisodesTable`. This takes the current sorting and filtering of the table into account. Then, when pressing the "Play" button, the uppermost incomplete episode is played instead of the most recently released incomplete episode.
This does not fully fix the issue as mentioned in https://github.com/advplyr/audiobookshelf/issues/1321#issuecomment-2492456282 because the sorting is applied to all podcasts instead of …
> Play first podcast episode in table

- test/server/migrations/v2.15.0-series-column-unique.test.js
This PR fixes the flaky test for the 2.15.0 migration test.
Same as https://github.com/advplyr/audiobookshelf/pull/4010
Each test now uses a fixed Date object for creation to ensure the test is no longer flaky.
During testing, I found that `LibraryAuthorController` tests are flaky and will usually fail within around 40-70 runs. The longest I saw was 84 runs before failing. Switching to running these tests in isolation (deleted all other tests because I am not sure how to disable them) still had errors at the same approximate frequency, so I think the `LibraryAuthorController` failure is not due to interactions with other tests.
Created a bash script which continuously runs `npm run test` until any test fails. The test ran successfully (without LibraryAuthorController tests) over 300 times …
> Fix: flaky 2.15.0 migration test

- client/components/tables/podcast/LazyEpisodeRow.vue
- client/components/tables/podcast/LazyEpisodesTable.vue
Adds a new sorting option (-> "Filename") to the podcasts view/table.
Fixes #3637
Locally stored podcast files often don't contain proper meta-data ("published date", "episode number", etc.); which is needed for reasonable sorting.
However, files that contain suitable name-prefixes (e.g. "20250213-podcast-xyz.mp3") can provide the necessary information that way.
Tested via dev-container setup.
> new sort option for podcasts view (-> sort by filename)

- server/providers/CustomProviderAdapter.js
Checks if the type is string before passing it to sanitize, because sanitize throws an error if the type is not a string.
Another way would be to return null if the type is not a string instead of the current way to prevent this happening altogether in the sanitizer.
I am not sure if this is possible, but if the type would not be a string, then it would not go through the sanitizer. So if the type is somehow not a string, one could maybe include bad code. I am not that familiar with JavaScript's type system, so I don't know if it's possible that this variable could be something other than a string, null, or a number when numbers would be returned.
> Fixes search not returning results if description field is not provided by a custom provider

- client/components/tables/podcast/LazyEpisodeRow.vue
Fix display of RTL description in Podcast episodes table.
No issue.
A couple of small fixes in `LazyEpisodeRow` subtitle/description display:
- Change \<p> to \<div> (since description can now contain \<p> tags)
- Add `dir="auto"` attribute (this determines the direction based on the content)
Loaded Hebrew (RTL) and English podcast pages
- Description now displayed correctly for Hebrew
- Unchanged for English
Before:
After:
> Fix RTL issue in LazyEpisodeRow

- server/Logger.js
- server/scanner/LibraryScan.js
- server/scanner/ScanLogger.js
Remove duplicate functions for logging.
No issue
This PR removes the duplicate `getLogLevelString` function from the scan-related loggers. `Logger` is already included, so this just removes code duplication.
This also increases the total coverage of the `Logger.test.js` with no changes to the test code.
Ran unit tests and a scan to ensure nothing broke.
N/A
> Simplify log level determination

- client/strings/en-us.json
- server/utils/scandir.js
Fix spelling in 'Settings/Scanner/Parse subtitles' info bubble. Same fix in a comment in a different source file.
n/a
n/a
n/a
> Fix spelling

- server/utils/parsers/parseEpubMetadata.js
Adds ability to load epub covers via [cover-image property](https://www.w3.org/TR/epub-33/#sec-cover-image) in manifest if the cover meta entry is missing.
Fixes #4105
The implementation respects the [EPUB 3.3 spec](https://www.w3.org/TR/epub-33/#attrdef-item-properties), and loads `property="cover-image maybe-other-props"` tagged manifest items as cover image, in case the cover metadata entry is missing. Fallback to the first image is still present if neither metadata entry, nor property can be found.
I've used this [epub](https://github.com/IDPF/epub3-samples/releases/download/20230704/epub30-spec.epub) as example where this can help. Simply importing this into ABS will have the wrong cover before this change, but the good one after reimporting it with the change. (Same cover as Calibre …
> Fix: Load epub covers via cover-image property

- server/scanner/OpfFileScanner.js
- server/utils/parsers/parseOpfMetadata.js
- test/server/utils/parsers/parseOpfMetadata.test.js
Parse OPF v3
See https://github.com/advplyr/audiobookshelf/discussions/4109
None
In OPF v3 [meta elements](https://www.w3.org/TR/epub-33/#sec-meta-elem) can have a `refines` attribute that is an ID of another element it is describing.
In this example the role of the `dc:creator` element is in the refines meta element.
```xml
<package version="3.0" unique-identifier="uuid_id" prefix="rendition: http://www.idpf.org/vocab/rendition/#" xmlns="http://www.idpf.org/2007/opf">
<metadata>
<dc:creator id="create1">Nevil Shute</dc:creator>
<meta refines="#create1" property="role" scheme="marc:relators">aut</meta>
<meta refines="#create1" property="file-as">Shute, Nevil</meta>
</metadata>
</package>
```
Added test case
> Update opf parser to support refines meta elements

- server/models/Book.js
Allow number types for payload metadata when updating books.
[4114](https://github.com/advplyr/audiobookshelf/issues/4114)
Allow the use of number types for payload metadata when updating books.
OpenLibrary uses numbers instead of strings to update the published year, so this PR attempts to fix this issue by allowing number types for payload metadata. 
I have replicated issue [4114](https://github.com/advplyr/audiobookshelf/issues/4114) locally and tested the change effects.
> Allow number types for payload metadata when updating books.

- client/components/app/Appbar.vue
- server/controllers/LibraryController.js
- server/routers/ApiRouter.js
- server/utils/zipHelpers.js
Adds a new endpoint that allows bulk downloading multiple library items and adds it to the frontend.
None directly, I think. But it comes close to #3541 and I believe this is the better approach instead of implementing an endpoint for Collections, Series, Authors, Playlists, etc.
It fetches all the library items and their paths, puts them into one zip file.
Structure is like
```
ZIP
-- file.mp3
-- Book Folder Name/
---- file.mp3
---- file.epub
```
We are limited by GET to download the file as it has a 2000 character limit on most browsers. Since we can't send any request body, we have a limit of 40 IDs we can send to safely prevent any errors. Therefore, the download button is only shown for up to 40 books. But in theory, it would work with more.
Using my own library. Files in root …
> Adds the option to download selected books

- client/pages/config/stats.vue
For "Items Finished" in stats page, replace SVG icon with equivalent Material Symbol ligature
I did not open an issue for this
Replaces the inline SVG element for the "Items Finished" stat with the equivalent symbol from the Material Symbol font to be consistent with the other stats.
Noticed this while idly selecting random text on the page and noticing that this icon was not selectable.
Manual edit in browser, did not actually build the program
Before:
After:
> Consistent icons in stats page

- server/utils/queries/libraryItemsBookFilters.js
- server/utils/queries/libraryItemsPodcastFilters.js
See #4163 
Users with permissions set that can limit the number of items shown on the library page can show the wrong count due to count caching.
Fixes #4163
This fix always skips the count cache for users with a tag restriction or a restriction on explicit content.
It would be too complicated to keep using the count cache for those users in its current implementation.
Tested with users with tag restriction and explicit content restriction.
> Fix items count for users with item restricting permissions

- .github/workflows/component-tests.yml
- client/cypress/tests/components/cards/AuthorCard.cy.js
- client/cypress/tests/components/cards/LazyBookCard.cy.js
- client/cypress/tests/components/cards/LazySeriesCard.cy.js
This fixes some broken client component tests
No issue.
Unfortunately, we don't run component tests automatically, so they break from time to time.
This fixes them to run with the current code.
If it's OK with you, I'll add these to the push procedure using a Github workflow (like unit tests).
All existing tests run.
> Fix broken component tests

- server/controllers/StatsController.js
- server/routers/ApiRouter.js
- server/utils/queries/adminStats.js
Create StatsController in preparation for new server stats page. Moves existing year in review stats endpoint to StatsController.
None
This also sets up a server stats endpoint at `/api/stats/server` that returns the following data so far.
```json
{
"books": {
"totalSize": 46370467418,
"numItems": 221,
"numAudioFiles": 2586
},
"podcasts": {
"totalSize": 9962023922,
"numItems": 70,
"numAudioFiles": 80
},
"total": {
"totalSize": 56332491340,
"numItems": 291,
"numAudioFiles": 2666
}
}
```
This will likely change as the server stats page gets realized.
> Create new StatsController and move year in review stats endpoint

- server/SocketAuthority.js
- server/controllers/AuthorController.js
- server/controllers/LibraryController.js
- server/controllers/LibraryItemController.js
- server/controllers/MiscController.js
- server/controllers/PodcastController.js
- server/managers/PodcastManager.js
- server/scanner/LibraryItemScanner.js
- server/scanner/LibraryScanner.js
- server/scanner/Scanner.js
Socket events sent out for `item_updated`, `items_updated`, `item_added` and `items_added` will check if user can access the library item before sending the event.
Fixed #4199
This sets up 2 additional socket event emitters: `libraryItemEmitter` and `libraryItemsEmitter`
These emitters check the socket client users permission to access the library item before emitting. `libraryItemsEmitter` will filter out items not accessible.
Tested a user with tag restriction and checked for socket events while editing items.
> Fix socket events check user permissions for library items #4199

- server/models/FeedEpisode.js
Fix server crash when a user requests the RSS feed of an empty collection. 
None/Discord
`reduce` needs at least one item in the array (or intial value). If the array is empty, it throws an error. Since the for loop is not called when `books` is empty, we can just make this null. The RSS feed will still be opened then. An alternative would be to close the RSS feed for any empty collection. I can imagine that this would not be a good solution, because if people remove an item and then instantly add one, it would be unexpected to have a closed RSS feed.
> Fix server crash when a user requests the RSS feed of an empty collection

- server/controllers/MiscController.js
When updating the "Ignore prefixes when sorting" list in server settings, the server will crash when a series name has to be updated.
Fixes #4221
When using the [updateOnDuplicate](https://sequelize.org/api/v7/interfaces/_sequelize_core.index.bulkcreateoptions#updateonduplicate) option to bulk update we have to pass in all key/values that have a unique constraint.
The unique constraint for `libraryId` and `name` was added in [v2.14.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.14.0) from PR #3417 
That was 8 months ago so I suspect this bug was actually introduced when updating to sqlite `v3.44.2` from `v3.41.1` for [v2.20.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.20.0). I wasn't able to find anything specific to this in the sqlite changelogs though.
> Fix server crash when updating excluded prefixes #4221

- client/components/player/PlayerTrackBar.vue
- client/pages/share/_slug.vue
Share audio player track bar tooltip overflows the page causing a horizontal scroll bar.
No issue
The track bar padding in the share player is larger than the regular player so the tooltip calculation was off.
This also disables the tooltip on mobile for both the share player and regular player. The tooltip should only be shown when hovering with the mouse.
Overflow
Fixed
> Fix player track tooltip overflowing on share player

- client/components/stats/YearInReviewBanner.vue
Allows users created in the same year to see some stats on the "Year in Review" page.
I could not find an issue regarding this. I could have maybe created one but just decided to fix it. 
I just started using AudiobookShelf and noticed that the stats page defaults to the previous year. It looks like there is some logic to allow users to select the current year but that is only if they have more than 1 available year.
I opted to keep that logic and only show previous year stats if those stats exist. In December users with more than one year will start to see their current year recap. New users will see previous year by default as soon as they pass into a new year after their account was created. 
I loaded the page for "Your Stats" with my user createdAt timestamp set with a year in 2025 to …
> Improves Year in Review display logic

- server/models/LibraryItem.js
- server/scanner/LibraryScanner.js
- server/utils/scandir.js
This update improves the watcher to support, for example, adding a cover image to an existing library item folder and triggering a re-scan for that item.
Fixes #4245
When the watcher detects files added/removed in a library folder it groups the files into potential library item paths. That grouping process distinguishes between media files and other files for the purpose of ignoring folders that only have non-media files. Other files are included in the grouping only if there is a media file in that potential library item group.
Note: These groups are "potential" library items because at that stage it is not confirmed whether those paths are existing library items.
This update changes that to allow for "scannable" non-media files (e.g. txt, nfo, png, json) to be included in the library …
> Update watcher to re-scan library items for non-media file only updates

- .gitignore
- client/components/ui/ToggleBtns.vue
- client/components/widgets/EncoderOptionsCard.vue
- client/pages/audiobook/_id/manage.vue
- client/strings/en-us.json
- server/controllers/LibraryItemController.js
- server/controllers/ToolsController.js
This improves the m4b encoder tool default values and the UI/UX on the audiobook tools page.
Fixes #4169 and fixes #1257
M4b tool improvements:
- Default to `copy` codec if all audio file codecs are AAC
- Select closest bit rate to one of 32k, 64k, 128k, 192k (instead of always 128k potentially increasing the size)
- Use mono channel if all audio files are mono (instead of always stereo)
- UI improvements
- Better breakpoints for mobile and small screens
- Use card with tabs for presets/advanced
- Show bit rate, channels, and codec in the audio tracks table
- Show the current bit rate, channels and codec below the presets (bit rate is averaged & channels use the max)
The preset defaults are best explained in the screenshots below.
When audio tracks are mp3's the default is to encode to …
> Audiobook tools enhancements

- client/players/AudioTrack.js
- client/players/PlayerHandler.js
- server/Server.js
This is a follow up on #4263 to update HLS streams to not use the user token in the URL.
No issue but related to #4259
The HLS stream URLs are structured `/hls/:sessionId/:file` and is only accessible while the session is open. Sessions are automatically closed after 36 hours.
Both direct streaming and HLS transcoding streams will use the session id in the URL.
> Update HLS stream endpoints to not include user token

- client/components/tables/podcast/LazyEpisodesTable.vue
This implements a secondary sort on the podcast episodes table.
Fixes #4262
When sorting by `Title`, `Episode` or `Filename` the secondary sort is `Pub Date`.
When sorting by `Season` the secondary sort is `Episode` with a tertiary sort of `Pub Date`.
Downloaded episodes from https://www.spreaker.com/show/4488937/episodes/feed and manually added seasons and episodes
Example sorting by season descending
Season -> Episode -> Pub Date descending
> Update episode secondary sort to pubDate and episode #4262

- client/components/modals/item/tabs/Tools.vue
- client/pages/audiobook/_id/manage.vue
- Audiobook tools page shows the m4b encoder option for single file m4b audiobooks.
- Replace the header with the item title and edit item button. Consistent with edit chapters page.
No issue
There is no reason to have the m4b encoder unavailable to single file m4b audiobooks. Supporting this will allow for re-encoding m4b audiobooks.
Changes to the header will allow for making edits to the item without leaving the tools page.
> Audiobook tools update

- server/utils/fileUtils.js
- test/server/utils/fileUtils.test.js
The .ignore file handling based on prefix was incorrect in edge cases.
The file "a/.ignore" should only cause the directory "a" to be ignored.
However, it also ignores all files starting with "a".
After this fix, it will only ignore paths starting with "a/".
Added unit test.
> Fix .ignore file causing ignores outside the directory

- Dockerfile
Reduces the final docker image size
no issue open
this adds a third stage to the build, copying the required files only from the previous stages, this reduces the final image size from 600MB+ down to ~320MB
I tried the image after the build and it seems to be working, is there a test suite to run?
> Reduce final docker image size

- client/components/app/BookShelfCategorized.vue
- client/components/cards/EpisodeSearchCard.vue
- client/components/controls/GlobalSearch.vue
- client/pages/library/_library/search.vue
- server/utils/queries/libraryItemsPodcastFilters.js
Add support for global search in podcast libraries to search episode titles.
Fixes #3301
In order to re-use the cards used for episodes on the home page, the returned `episodes` from the search endpoint is an array of library items with a `recentEpisode` attached.
Episode cards shown on the search page are the same as those shown on the home page. Episodes shown in the global search dropdown show the podcast cover, episode title and podcast title.
To stay consistent with the podcast/book search, I didn't add the description to the query. It may not be worthwhile to add the description until the search is improved to better sort best match.
This is also tested with users that don't have access to the podcast.
> Add support for searching podcast episode titles #3301

- client/components/modals/podcast/EpisodeFeed.vue
- server/Server.js
This increases the limit of [express.json](https://expressjs.com/en/api.html#express.json) from 5mb to 10mb.
And updates the check when downloading episodes that prevents too large of requests.
Fixes #4250
Increasing the limit allows for downloading more episodes in a single request. This is the only place in the app where JSON requests of that size are sent. We could break up the request into multiple and keep them under 5mb, but having a 10mb limit seemed reasonable.
Example RSS feed: https://feeds.simplecast.com/54nAGcIl
When adding this podcast and selecting all episodes to download at once, the request size is around 9.7mb. This is now supported.
> Update max allowed json request size #4250

- server/models/MediaProgress.js
When a local playback session is synced the `lastUpdate` time should be set on the media progress object to the same value. This way when comparing the timestamps for syncing they will be the same on the mobile device and server.
This was not working properly because Sequelize requires passing `silent: true` when saving.
I don't believe this is the underlying issue with progress syncing on mobile but if these timestamps are lined up it will be easier to debug.
I found this while testing local progress syncing: https://github.com/advplyr/audiobookshelf-app/issues/1510#issuecomment-2902671752
Note the log:
The progress was more recent on the server because of the bug being fixed in this PR. But you can see this was no problem because the `currentTime` on the server and the device were the …
> Fix MediaProgress not using the lastUpdate time sent for local progress syncs

- server/controllers/PodcastController.js
- server/models/Book.js
- server/models/Podcast.js
This is an API update to sanitize HTML descriptions
No issue, related to #4349
API endpoints `/items/:id/media` and `/api/podcasts/:id/episode/:episodeId` support updating the description for book/podcast & podcast episodes.
Since those descriptions support HTML they need to be sanitized.
Sanitization options
```js
{
allowedTags: ['p', 'ol', 'ul', 'li', 'a', 'strong', 'em', 'del', 'br', 'b', 'i'],
disallowedTagsMode: 'discard',
allowedAttributes: {
a: ['href', 'name', 'target']
},
allowedSchemes: ['http', 'https', 'mailto'],
allowProtocolRelative: false
}
```
API
> Sanitize media item & episode description on update

- server/managers/PodcastManager.js
From the logs, I strongly suspect that the timeout for the feed request never triggers, which causes the code to hang. As a result, it is never removed from the executing list and is not executed again. To check this (since it is possible that the ssrf filter interferes with the timeout), I added a promise that will throw after the timeout to ensure it works. If this works, we will know that it has something to do with axios and can implement a better fix. This change does not affect any behavior and still allows axios to fail correctly (with an extra second), so it should be safe to merge.
Potentially fixe s https://github.com/advplyr/audiobookshelf/issues/4098
Own podcasts with 1 minute cron and custom timeout values
> Potential fix/new knowledge for hangig podcasts

- client/components/ui/VueTrix.vue
Currently, files can be added to the editor, which I think is nice and could be brought back in the future. However, because the description is sanitized,(btw. ignore name of branch. Not possible because of sanitization). I noticed that files can be pasted, including images, so maybe we should consider allowing files in the future, but right now, sanitization removes them when the description is saved. To get parity now all attachments are disallowed, also including files
Maybe there's a reason we allowed files that I missed (in that case, please close this), but at the moment, you can add files (such as images or Excel files) that are just lost after saving.
None
See description
Copy pasting images and files
> Corrects removing of attachments for Trix

- server/Database.js
Adds a step in the clean database function to remove duplicate `mediaProgresses` entries
No issue, but related to #4366 and probably others. This is often brought up in Discord.
A race condition in the API when syncing sessions and/or creating media progress can result in multiple media progress records with the same `mediaItemId`. So far this is only seen with the third party app Plappa.
This PR doesn't fix that issue but it will clean up the duplicates on server startup.
Created duplicates in the db manually
> Update cleanDatabase to remove duplicate mediaProgresses

- server/controllers/FileSystemController.js
This is a follow up to #4342 to fix an edge case
No issue
When using `Path.posix.join` with a posix file path and a Windows file path the resulting join isn't normalized.
For example:
```js
Path.posix.join("C:/Users/Test/audiobooks", "..\\test")
```
returns `C:/Users/Test/audiobooks/..\test`
`Path.join` returns `C:/Users/Test/test` as expected
This is an issue because `fs.pathExists` is normalizing the posix and non-posix path
Making API calls. The web ui doesn't use relative paths.
> Fix filesystem pathexists path join

- server/utils/ffmpegHelpers.js
Some podcasts fail with different user agents
Fixes #4401
Related #3246
Related #3322
This will have podcast episode downloads fallback to another user agent string on any failure.
Primary user-agent: `audiobookshelf (+https://audiobookshelf.org; like iTMS)`
Fallback user-agent: `audiobookshelf (+https://audiobookshelf.org)`
RSS feed: https://www1.nobexpartners.com/getfeed.ashx?id=46434&list=LIRAZ
Can download with the primary user-agent but not the fallback user-agent (reported in #4401)
RSS feed: https://feeds.captivate.fm/james-obrien-the-who/
Fails to download using the primary user-agent but works with the fallback (reported in #3246)
A related user-agent issue was with requesting the RSS feed (not downloading) for CBC podcasts (reported in #3322)
The user-agent was first added here …
> Update podcast episode downloads to have a fallback user agent string

- client/components/modals/podcast/ViewEpisode.vue
Podcast episode descriptions that have timestamps can be clicked to open the player at that time.
No issue but matches the mobile app https://github.com/advplyr/audiobookshelf-app/pull/1208
and an incomplete attempt at this https://github.com/advplyr/audiobookshelf/pull/4386
Parsing timestamps uses the same regex that has been tested in the mobile app the last year.
> Episode view modal makes timestamps in description clickable

- index.js
- server/Auth.js
- server/Server.js
When ENV variable `REACT_CLIENT_PATH` is set the server will start a next.js app at the location instead of serving the nuxt app.
This is for testing a separate React frontend.
As of now the goal is to replace Nuxt with React (probably Next but not certain) and to keep the frontend in a separate repo from the server.
In the following days I'll set up a repo for the client. I have one on my local that is working well but needs to be cleaned up.
Some of the main reasons for choosing Next:
- Works with CJS (including SSR)
- `pkg` can create binaries for Windows/Debian
- HMR in development works out-of-the-box without running another process
> Add ENV REACT_CLIENT_PATH to target a Nextjs frontend instead of Nuxt

- server/scanner/LibraryItemScanner.js
- server/scanner/LibraryScanner.js
- server/utils/fileUtils.js
When deleting a single file book via the web ui the scanner re-adds the item
Fixes #4459
Reproducible steps in #4459 
The issue is single file books in the root folder don't run `recurseFiles` that is normally run on a folder getting scanned in. The single file book is not checked if it exists like a folder is.
This PR updates the scanner to add that check. It will also bail earlier when a scan runs after deleting a library item folder.
I also updated the file utils `getIno` to log a warning instead of an error since it is not an error when a file doesn't exist.
> Fix scanner after deleting single file books #4459

- server/auth/OidcAuthStrategy.js
- server/auth/TokenManager.js
- server/models/User.js
The OIDC auth refactor caused the generate access token function to be unavailable when auto registering a user.
This adds a static generate token function.
When the old auth method gets removed this won't be necessary and those functions will be removed.
Fixes #4485
> Fix OIDC auto register user #4485

- client/components/modals/ListeningSessionModal.vue
- client/pages/config/users/_id/index.vue
- client/strings/en-us.json
- server/controllers/SessionController.js
- server/controllers/UserController.js
Sessions modal shows username instead of user id.
`/api/sessions` and `/api/users/:id/listening-sessions` endpoints always return a user object with sessions that includes `id` and `username`.
Adds a warning message under the legacy token input to use API Keys instead.
Fixes #4496
> Update sessions modal to show username & update legacy token input with warning

- server/controllers/SessionController.js
- server/models/PodcastEpisode.js
Make sure podcast episode audio track index is always 1 in playback sessions & support 1 or 0 track index in the direct play endpoint.
Fixes https://github.com/advplyr/audiobookshelf-app/issues/1635
In [v2.21.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.21.0) a bug was fixed where podcast episodes scanned in from the file system had an audio track with an index of `null`. https://github.com/advplyr/audiobookshelf/commit/7c114a051a08d401b5b6dded1620a6f1f92f05c0
In [v2.22.0](https://github.com/advplyr/audiobookshelf/pull/4263) new API endpoints for direct playing was added that use the audio track index in the url.
When playing an episode with an index value of `null` in the web client it falls back to transcoding because the track isn't found.
In mobile app v0.10.0-beta the …
> Fix podcast episode track index null in playback session

- client/components/readers/EpubReader.vue
- client/components/readers/Reader.vue
- client/strings/en-us.json
This PR introduces a `sepia` theme option for the Epub Reader. Simple theme option, allowing for better readability and retaining same functionality as other themes.
Fixes #4407
Summary of Changes
Sepia mode in themeRules():
Detect when ereaderSettings.theme === 'sepia' and set fontColor = '#5b4636' and backgroundColor = 'rgb(244,236,216)'
Leave all other style rules (line-height, text stroke, link color) unchanged as for dark/light.
Data-attribute utilities on main reader container:
Added data-[theme=sepia]:bg-[rgb(244,236,216)] and data-[theme=sepia]:text-[#5b4636] alongside existing dark/light variants.
Group-aware utilities on TOC sidebar:
Added group-data-[theme=sepia]:bg-[rgb(244,236,216)] and group-data-[theme=sepia]:text-[#5b4636] to mirror the sepia styles.
With these updates you …
> Add 'sepia' theme to EpubReader

- client/pages/audiobook/_id/chapters.vue
Issue #4226 introduced the ability to remove the audible branding when editing chapters. While it does this well for the chapters themselves, all other validations do not account for it. This update is to remove the branding times from the runtime totals as well.
Related to #4226
Although the branding times are removed and the chapters are shifted, you will always receive the warning that the total time doesn't match you local audio files. This is because the #4226 feature didn't also remove the branding from the total runtime. This update also removes the intro/outro branding times from the total duration, which is used in the validation logic.
I did not test this. Not sure how.
The branding time in the example below is 6,873 millis, which results in the difference of 7 secs.
> Including total durations into the de-branding from #4226 as warning message is always present currently

- client/layouts/default.vue
- client/pages/login.vue
- client/store/libraries.js
- client/store/user.js
Fixes a race condition happening when refreshing the access token on initial page load.
Fixes #4567
When refreshing the access token on `/api/authorize` the response from the `/auth/refresh` is updating the user. This user update is triggering the user watcher in `login.vue` before the default library id is set.
There is no reason to update the user from the token refresh response so that is removed
> Fix authorize race condition by not updating the user on token refresh

- server/managers/PodcastManager.js
- server/objects/PodcastEpisodeDownload.js
This removes the `isMp3` check that was used to only embed meta tags in mp3 podcast episodes. Now all episode downloads will attempt to have meta tags embedded and fallback to a regular download.
None, discussed in Discord
A tangentially related issue to this is that some podcast RSS feeds provide the wrong file extension. For example, in #3837 the podcast has `.mp3` file extension but the files are actually mp4. In this case the ffmpeg meta tag embed will fail and the episode will fallback to being downloaded without meta tagging.
Example RSS feed with 3 `.m4a` files: <https://anchor.fm/s/370d6ccc/podcast/rss>
Example RSS feed with `.ogg` files: <https://feeds.feedburner.com/TheLinuxLinkTechShowOgg-vorbisFeed>
> Update podcast episode downloads to always attempt embedding meta tags

- server/Server.js
Fix incorrect listening url in log when use ipv6 host
Run with ipv6 host return incorrect url in log:
```
> node index.js --host ::
...
[2025-08-16 17:55:56.554] INFO: Listening on http://:::12378
...
```
After change:
```
> node index.js --host ::
...
[2025-08-16 17:55:56.554] INFO: Listening on http://[::]:12378
...
```
> Fix listening url log with ipv6 host

- server/auth/OidcAuthStrategy.js
NPM, even if it's not the spec, returns `'x-forwarded-proto': 'http, https',` as header. 
Fixes #4609 
See Discord conversation. This is basically because NPM adds both protocols as forwarded.
Local NPM setup
> Fix Invalid callback URL - must be same-origin for NPM users

- client/components/ui/MultiSelect.vue
This PR adds a unique identifier to the Vue for loop to ensure all keys have a unique identifier.
Related to https://github.com/advplyr/audiobookshelf/issues/4634
If the same key exists multiple times in a MultiSelect component, the unique key requirement for `v-for` is violated. By adding an index to the key, we ensure that every key is unique, but do not change the values displayed in the front-end.
This can only happen if the database incorrectly includes the same value in an array, such as the same tag applied to the same book multiple times. Instead of filtering out the duplicate tags, these should be displayed to ensure consistent behavior when comparing against the API or another client and allow the user to fix the duplicate tag.
This does not fix the root of the problem where the …
> Fix: MultiSelect causes web client to become unresponsive if duplicate keys exist

- server/managers/PodcastManager.js
- server/utils/ffmpegHelpers.js
Update podcast episode downloads to fallback to regular download if the ffprobe fails.
None, mentioned on Discord
A private patreon podcast RSS feed that has m4a audio files is unable to be streamed into ffmpeg for download. The audio file gets downloaded with no media streams so the ffprobe fails.
This update moves the non-ffmpeg fallback download to after the ffprobe.
This resolves that patreon RSS feed
> Fix issue with episode downloads without streams
