client/components/app/Appbar.vue, client/components/app/BookShelfToolbar.vue, client/components/app/SideRail.vue, client/components/controls/OrderSelect.vue, client/components/modals/libraries/LibraryItem.vue, client/components/tables/LibrariesTable.vue, client/store/libraries.js, server/ApiController.js, server/Server.js, server/objects/AudioFile.js, server/objects/Audiobook.js, server/scanner/AudioFileScanner.js, server/scanner/AudioProbeData.js, server/scanner/Scanner.js
Added a force rescan button to the library settings page.
=> Add: Force re-scan library

client/components/modals/edit-tabs/Match.vue, server/BookFinder.js, server/providers/Audible.js
Stop gap measure until the Audible API is back to full functionality, but it's probably worth it to keep in there for those times that the Audible search has a hard time finding the right book.
=> Added ASIN support in the title field

server/controllers/BookController.js
Pick a cover from local image list dont change the cover, because cover is not removed from cachemanager.
=> Fix local cover change dont work

server/utils/libraryHelpers.js
=> Sort filters ascending

server/controllers/FileSystemController.js
` UnhandledPromiseRejectionWarning: ReferenceError: Path is not defined at /server/controllers/FileSystemController.js:8:7 ...`
=> Bug: Missing path variable

server/providers/Audible.js, server/providers/Audnexus.js, server/providers/GoogleBooks.js, server/providers/LibGen.js, server/providers/OpenLibrary.js
Fixes https://github.com/advplyr/audiobookshelf/issues/275 and other possible places
=> Fix: escape special characters in provider urls

server/objects/AudioFileMetadata.js, server/objects/Book.js, server/utils/prober.js
If file metadata has isbn tag it will be fetched and used for book
=> Added isbn fetching for metadata

client/pages/audiobook/_id/index.vue
Book info editor was showning line changes, but not book view.
=> Book view shows line changes on description

client/components/covers/GroupCover.vue
#321 
Limit is currently 30, i think thats a good balance
=> Limit group cover

server/controllers/LibraryController.js, server/utils/libraryHelpers.js
Added section to home with next book in any series that has been started.
=> Add continue series category to home

client/components/covers/GroupCover.vue
#321 
I will edit the amount of showed covers based on #321.
=> Fix: Group cover does not use full width

server/utils/parseOpfMetadata.js
Added getting narrators from calibre custom column in opf files.
=> Fetch Narrators from opf custom column

client/components/modals/item/tabs/Match.vue
Nitpicking verbiage tbh. Reference: https://github.com/advplyr/audiobookshelf/issues/431
=> Change 'Current' to 'Currently'

.gitignore, client/components/modals/podcast/EpisodeFeed.vue, client/components/modals/podcast/NewModal.vue, server/Server.js
Added checkbox to select all episodes so that they can be downloaded all at once
=> Added select all option to the episode selector

client/package-lock.json, package-lock.json
Tested and images available
Updates Only: `jflattery/abs-dev:package-upgrades`
Updates & Dedupe: `jflattery/abs-dev:dedupe`
=> Update and dedupe packages

client/components/app/Appbar.vue, client/components/tables/podcast/EpisodeTableRow.vue, client/components/ui/Menu.vue, client/components/widgets/CoverSizeWidget.vue
Add episode number to list group view
=> podcast episode number & accessibility improvements

server/managers/PodcastManager.js
Add podcast title to log output when autodownload fails
=> Increase readability of logs

readme.md
As per Discord discussion, adding this to help others if they get this issue.
=> Temp Fix for Unknown Error in App with Traefik

readme.md
Add instructions for both versions of docker compose
=> Docker Compose Update Instructions

client/components/modals/podcast/EpisodeFeed.vue, client/package-lock.json, package-lock.json, readme.md
Fix for Podcasts such as "Beers with Talos" who don't publish their feed in a chronological order
=> Fix for unsorted feeds, update npm, add docker tag

package.json
Allows launching of server with npm run watch, which automatically restarts server upon changes made to .js files within audiobookshelf/server
=> Added support for npm run watch

server/objects/metadata/BookMetadata.js, server/utils/scandir.js
Scanner looks for {tags inside curly braces} and interprets them as narrators.
=> Scan for narrator

server/utils/scandir.js
Minor tweaks to the way scanner handles information about series volumes.
=> Get book data from dir refactor

server/managers/AudioMetadataManager.js
Added support for chapter metadata in #678, but completely missed that coverart wasn't getting embedded in the embed metadata tool. This commit adds that in.
I tested this by putting an m4b in my library, scraping a new cover, embedding the metadata through the embed tool, and then opening in VLC to validate the new cover is there
=> Support embedding cover art metadata in the embed metadata tool

server/utils/scandir.js
=> Fixed bugs that caused getSequence to run twice and broke year recognition

server/utils/parsers/parseOverdriveMediaMarkers.js
Couldn't figure out how to get my editor to do this properly earlier. Figured it out now though. Updating this file to match the rest
=> Fix indents from 4 spaces to 2 in parseOverdriveMediaMarkers.js

client/pages/config/stats.vue
This PR resolves Issue #760 
**Before**
**After**
=> Fix truncation on your stats page (Issue #760)

server/finders/BookFinder.js
This PR looks to resolve issue #794 
We weren't properly awaiting the responses from the different provider search results. For iTunes and Google, this didn't result in any end user facing issue, but for Audible, it would cause an empty response to get returned after the actual response did when searching by ASIN.
I'm... not super confident in my understanding of async/await in JS, but this definitely seemed to cause some mildly unoptimal code. In the logs below, you can see in the After state, that we no longer need to unnecessarily do the 2nd search against "cleaned title and author" for any of the providers.
**Before**
```
Audible (search by ASIN)
[2022-06-29 19:27:22] DEBUG: Book Search: title: "B004TNLOV8", author: "", provider: audible
server/Logger.js:87
[2022-06-29 19:27:22] …
```
=> Fix issue with unecessary empty search during match (Issue #794)

client/components/app/BookShelfToolbar.vue, client/pages/library/_library/bookshelf/_id.vue
This seems like a clean way to do this.  Although I've never used Vuex so feel free to slap my wrist if this isn't right.
=> Pass lib ID to toolbar so it can refresh state when clearing issues.

server/libs/nodeFfprobe/index.js
=> Issue 1004

package-lock.json, package.json
Simple commit that makes it so that the server code supports live reload. I've tested it and it works really nicely. I know the client already had this option, so adding it to the server only made sense.
=> Makes the dev target support auto reloading of the server

client/pages/audiobook/_id/manage.vue, server/controllers/LibraryItemController.js, server/managers/AbMergeManager.js, server/managers/AudioMetadataManager.js, server/utils/toneHelpers.js
This is an academic PR, I haven't been able to test it, but the logic checks out in my head haha.
=> Added tone json file support

client/components/app/Appbar.vue, client/components/cards/AuthorCard.vue
This patch adds a few more missing tooltips to the user interface.
=> Add Missing Tooltips

client/components/app/Appbar.vue
A string which is translated was hard coded...
I just changed it.
=> Missing Localization in Appbar.vue

readme.md
An example Caddyfile based on what I use
=> Add Caddyfile example to readme

client/strings/fr.json
Update for the latest addition
=> Update fr.json => ButtonEdit

images/banner.svg
All I did was open the banner in Inkscape, go to "Document Properties", clicked the "Resize to content" button, and exported it as a plain SVG.
Before, the view box clipped the right edge of the logo.
=> Fix banner view box

package-lock.json, package.json
This patch updates the server libraries to their latest state.
=> Update Server Libraries

client/pages/config/item-metadata-utils/index.vue
Localization was used elsewhere but was plain-text in this file
=> Patch localization Item Metadata Utils Header

client/components/app/StreamContainer.vue
Closes #1616 
Before:
https://user-images.githubusercontent.com/48161361/226457767-21bcef5d-c314-42a4-96d9-62a77d09c51b.mp4
After:
https://user-images.githubusercontent.com/48161361/226457919-37cfa265-3057-4098-8da2-7690d2fbe8af.mp4
=> Truncate long title in stream container

.devcontainer/Dockerfile, .devcontainer/dev.js, .devcontainer/devcontainer.json, .devcontainer/post-create.sh, .gitattributes, .gitignore, .vscode/launch.json, .vscode/tasks.json, readme.md
As requested in #259, I have tried to create documentation about setting up the development environment and running this project. As part of this effort, I also updated the .devcontainer used by visual studio code. For this, I regenerated the base configuration using VSCode, then added the necessary modules based on the Dockerfile in the root directory. I also added post-build commands to ensure everything was setup for new users. Finally, I added VSCode build/test tasks and debug targets.
If people use the dev container, it takes running one command in VSCode and hitting F5 before they are running the code for the first time, which is pretty nice.
=> Development documentation

client/strings/fr.json
Quick translation for new label
=> MessageConfirmRemoveAllChapters translation fr

client/components/app/BookShelfToolbar.vue, client/components/cards/AuthorCard.vue, client/components/modals/authors/EditModal.vue, server/controllers/AuthorController.js, server/finders/AuthorFinder.js, server/providers/Audnexus.js
as this should be supported now by audnex.us
https://github.com/laxamentumtech/audnexus/issues/609#event-9015163203
=> Use region for author queries

client/components/modals/item/tabs/Match.vue
=> fix: Make sure all existing genres also show up on the match tab

client/components/app/StreamContainer.vue
Related to https://github.com/advplyr/audiobookshelf/issues/1721
=> seek instead of skip with action handlers

server/Server.js
=> Fix: decode filename as utf8 on upload

server/objects/Stream.js
as discussed in https://github.com/advplyr/audiobookshelf/issues/2157
=> make force transcode apply to all "ffmpeg error 1"

docker-compose.yml
Added comments to make the docker compose more clear and allow it to be linked to from the website to help keep the compose file up to date.
=> Added comments to the Docker Compose file

client/strings/fr.json
=> Little Missed Update fr.json

readme.md
Add example for HAproxy and PFsense with HAproxy
=> README, add HAproxy example

client/store/globals.js
=> added raw cover on lockscreen for iOS

client/nuxt.config.js
=> PWA (iOS) theme color fix

client/strings/pt-br.json
=> Updated pt-br string

server/Auth.js
When using OpenID
Also added debug information on openid errors (so it does not just show OBJECT object)
=> Auth: Fix crash on missing logout URL

client/components/ui/TextInput.vue, client/pages/login.vue
To increase the likelihood for password managers to detect the username field, I added the `name` attribute to the username input field (and for the password filed too because it cannot hurt).
P.S.: I don't know if this is the right way of implementing this (I never worked with vue.js before).
=> Add name labels to login form

.github/workflows/i18n-integration.yml
This workflow runs an integration check to make sure that i18n JSON files have keys in an alphabetical order.
=> Add i18n integration workflow

readme.md
Added link to the new translation guide on the website for the web client.
=> Translation guide link added to readme

.github/workflows/i18n-integration.yml, client/strings/es.json
This PR fixes the `i18n-integration` action not running on PRs.
Also updated to a newer version of the action which will report if keys are misspelled in another language files (such as was needed for https://github.com/advplyr/audiobookshelf/commit/36c1a8b2df9c2a60a7b807c2dacd44018e54bbd6)
=> I18n integration fix

.github/ISSUE_TEMPLATE/bug.yaml
This PR adds more dropdowns and fields. Based on the Kavita issue template.
=> Issue Bug template updates

client/pages/config/email.vue
Fixes https://github.com/advplyr/audiobookshelf/issues/2917
=> Add: link to guide for email settings

.github/ISSUE_TEMPLATE/feature.yml
Built a new feature request form with much assistance and input from a friend who does this for her job and my spouse who is an expert user. (Edit to add: doesn't mean things can't change, just had lots of brainstorming)
Screenshots of it below (was too long for a single screenshot) and available at the following repo.
https://github.com/nichwall/issue_testing/issues/new?assignees=&labels=enhancement&projects=&template=enhancement.yaml&title=%5BEnhancement%5D%3A+
=> Add: new feature request form

client/components/readers/EpubReader.vue, client/components/readers/Reader.vue, client/strings/bg.json, client/strings/bn.json, client/strings/cs.json, client/strings/da.json, client/strings/de.json, client/strings/en-us.json, client/strings/es.json, client/strings/et.json, client/strings/fr.json, client/strings/gu.json, client/strings/he.json, client/strings/hi.json, client/strings/hr.json, client/strings/hu.json, client/strings/it.json, client/strings/lt.json, client/strings/nl.json, client/strings/no.json, client/strings/pl.json, client/strings/pt-br.json, client/strings/ru.json, client/strings/sv.json, client/strings/uk.json, client/strings/vi-vn.json, client/strings/zh-cn.json, client/strings/zh-tw.json
Update font settings in EpubReader and Reader components to include a "Font Boldness" slider which applies a stroke to the text per issue #3020
=> E-Reader Font Boldness Slider #3020

readme.md
This PR updates the translation section (and autoformats the entire file) of the readme to use Weblate. This PR should not be merged until everything is finalized.
=> Translation readme update

docs/controllers/EmailController.yaml, docs/controllers/NotificationController.yaml, docs/openapi.json
Fixes the linting errors from the 2.11.0 version bump release 93114b2181d1ee5f0026fcf04c0a2946e3e96641
https://github.com/advplyr/audiobookshelf/actions/runs/9830834509
=> Email notification linting fixes

docs/controllers/PodcastController.yaml, docs/objects/mediaTypes/Podcast.yaml, docs/openapi.json, docs/root.yaml
This PR updates the OpenAPI spec of podcast endpoints for OPML from 37ad1cc
=> Update: podcast opml endpoints

client/package.json
=> Moved cypress to `optionalDependencies`

server/managers/BinaryManager.js
This is in continuation to our discussion in #3199, in which we decided not download binaries from Github due to rate-limiting on unauthenticated API requests.
This re-implements downloading from ffbinaries (using roughly the same class and methods used for downloading from Github, and _not_ introducing back libs/ffbinaries), and removes support for Github downloading.
=> Go back to downloading binaries from ffbinaries.com

server/controllers/LibraryItemController.js
=> Fix Content-Type header when browser user-agent is from an Apple mobile device

client/package-lock.json, client/package.json
[since nuxt2 has passed it's EOL date,](https://nuxt.com/blog/nuxt2-eol)
i thought i'd try seeing if the bump from 2.17 to 2.18 would pass the github checks,  
and my git branch push did.
are there any more steps to do?  
am i missing anything?
=> client update: nuxt 2.17.3 -> 2.18.1

.github/workflows/docker-build.yml
This PR introduces [OpenContainer (OCI)](https://opencontainers.org) image format [annotations](https://specs.opencontainers.org/image-spec/annotations/) as labels to the built Docker images. The labels are already automatically extracted using the [Docker Metadata Action](https://github.com/docker/metadata-action) in the GitHub Action workflow, ensuring consistent and accurate metadata is applied to the image during the build process. However, this information was not yet passed to the image build process. 
- __Automated Metadata Generation__: The Docker Metadata Action automatically extracts relevant information such as the image’s title, description, source, version, revision, and more. This eliminates manual intervention and ensures the labels remain accurate and up-to-date with each …
=> Add OpenContainers Annotations as Labels to Docker Image

server/controllers/LibraryItemController.js
Fixes #3344
This PR adds proper error handling for file the following file download APIs:
- `/api/items/:id/download`
- `/api/items/:id/file/:fileid/download`
- `/api/items/:id/ebook/:fileid`
=> Add proper error handing for file downloads

server/controllers/LibraryItemController.js
Sorry, this is to fix the crash reported [here](https://github.com/advplyr/audiobookshelf/pull/3553#issuecomment-2445031131).
=> Fix incorrect call to handleDownloadError

docker-compose.yml
Updates the incorrect use of environment variable for running as a non-root user.
=> Update: user directive in docker compose file

server/managers/MigrationManager.js
If the rows do not exist, the migration manager crashes.
This fixes https://github.com/advplyr/audiobookshelf/issues/3588 by checking that both `version` and `maxVersion` are defined in the `migrationsMeta`. This PR drops the table and triggers the creation of the `migrationsMeta` table again if either row is missing.
=> Check that `migrationsMeta` table is well formed instead of just existing

server/scanner/AudioFileScanner.js, server/utils/scandir.js, test/server/utils/scandir.test.js
Support "Disc 1"-style disc folder names in addition to the current "CD01".
Fixes  #934
A few basic test cases via https://regexr.com/.
=> Support additional disc folder names

server/controllers/LibraryItemController.js, server/managers/AudioMetadataManager.js, server/managers/CoverManager.js, server/managers/CronManager.js, server/managers/PlaybackSessionManager.js, server/models/Book.js, server/models/LibraryItem.js, server/models/Podcast.js, server/models/PodcastEpisode.js, server/objects/LibraryItem.js, server/objects/mediaTypes/Book.js, server/objects/mediaTypes/Podcast.js, server/scanner/AudioFileScanner.js, test/server/controllers/LibraryItemController.test.js
Same as https://github.com/advplyr/audiobookshelf/pull/3761 but for the LibraryItem model
This handles endpoints in LibraryItemController
=> Refactor LibraryItem to use new model

server/controllers/SessionController.js, server/controllers/ShareController.js, server/managers/PlaybackSessionManager.js, server/models/Book.js, server/models/FeedEpisode.js, server/models/LibraryItem.js, server/models/MediaItemShare.js, server/models/Podcast.js, server/models/PodcastEpisode.js, server/objects/LibraryItem.js, server/objects/PlaybackSession.js, server/objects/Stream.js, server/objects/entities/PodcastEpisode.js, server/objects/mediaTypes/Book.js, server/objects/mediaTypes/Podcast.js, server/objects/metadata/BookMetadata.js
Continuation of https://github.com/advplyr/audiobookshelf/pull/3779
Handles PlaybackSession and manager
=> Update PlaybackSession to use new library item model

client/components/modals/podcast/EditEpisode.vue, client/components/modals/podcast/tabs/EpisodeDetails.vue, server/controllers/PodcastController.js, server/managers/CronManager.js, server/managers/PodcastManager.js, server/models/Podcast.js, server/models/PodcastEpisode.js, server/objects/PodcastEpisodeDownload.js, server/objects/entities/PodcastEpisode.js, server/objects/mediaTypes/Podcast.js, server/utils/ffmpegHelpers.js
Continuation of https://github.com/advplyr/audiobookshelf/pull/3779
Handles PodcastController
=> Update podcasts to new library item model

client/components/app/MediaPlayerContainer.vue, client/components/modals/BookmarksModal.vue, client/components/modals/bookmarks/BookmarkItem.vue, client/pages/item/_id/index.vue, client/strings/bg.json, client/strings/bn.json, client/strings/ca.json, client/strings/cs.json, client/strings/da.json, client/strings/de.json, client/strings/en-us.json, client/strings/es.json, client/strings/et.json, client/strings/fr.json, client/strings/he.json, client/strings/hr.json, client/strings/hu.json, client/strings/it.json, client/strings/lt.json, client/strings/nl.json, client/strings/no.json, client/strings/pl.json, client/strings/pt-br.json, client/strings/ru.json, client/strings/sl.json, client/strings/sv.json, client/strings/uk.json, client/strings/vi-vn.json, client/strings/zh-cn.json, client/strings/zh-tw.json
1. Update timestamps to scale with playback rate.
2. Update UI colors to be consistent with other modals.
3. Update create input to be outside of scrollable container so it is always visible.
4. Editing bookmark no longer closes modal
5. Removed edit bookmark success toast
Fixed #3728
Old:
New:
=> Bookmark modal updates

server/Database.js
Adds the new title[IgnorePrefix] update triggers (introduced in v2.19.1 and v2.19.4 migrations) if they don't exist, to handle new databases (for which migrations do not run).
Fixes #4003 
When triggers were added in migrations v2.19.1 and v2.19.4, I forgot to create those triggers in new databases, for which migrations don't run. Therefore, the new libraryItems columns title and titleIgnorePrefix were not updaed after a title was changed in a book or podcast, and the sort order wasn't updated.
I added code in Database.js to create the triggers if they don't exist.
Made sure that books/podcasts were correctly sorted after a title change in a newly created database (using edge code).
=> Add title triggers in new databases

client/components/modals/podcast/EpisodeFeed.vue, client/pages/item/_id/index.vue, server/managers/PodcastManager.js, server/objects/PodcastEpisodeDownload.js
This PR checks if an episode download is already queue to prevent the same episodes being added multiple times.
Fixes https://github.com/advplyr/audiobookshelf/issues/2672 and https://github.com/advplyr/audiobookshelf/issues/4036.
Before adding a podcast episode to the download queue, the server checks to make sure the URL and Library Item ID does not already exist in the download queue and is not already downloading. I am checking the Library Item ID in case the same podcast has been added to multiple libraries, such as having a dedicated podcast library for individual users who may have added the same podcast.
This does not fully solve the issue where:
1. A user can open the "Find Episodes" modal and add a number of episodes to the download queue
2. Reopen the "Find Episodes" modal …
=> Prevent duplicate episodes from being added to queue

server/managers/MigrationManager.js
Migration manager validates migration files on init.
Fixes #4042
As seen in #4042 and #3510 sometimes files get created in the migrations folder.
When getting files inside the migrations folder dot files are already being ignored.
With this update any file that is not a `.js` file is ignored.
Also, the `.js` files that are found are validated first to make sure they contain a version string, if not an error is thrown. This will help identify issues with filenames in the future.
Tested by including non-js files, dot files, and js files without a proper name.
=> Update migration manager to validate migration files #4042

server/routers/ApiRouter.js
This PR fixes an issue where the `LibraryItemController` test would fail occasionally.
No issue number, referenced in https://github.com/advplyr/audiobookshelf/pull/4055.
This PR changes the "author with zero books" check to happen in a Sequelize transaction to ensure race conditions do not happen due to changes in the database between checking the database and deleting the author. This PR also changes the "series with zero books" check to work in the same way.
The issue was specific to the "series with zero books" check. The change to the author function is not strictly necessary, but may as well add the transaction so it does not become an issue in the future.
The previous version of "series with zero books" check would then iterate over each series to do the following actions:
- Check …
=> Fix empty series delete check

server/models/MediaProgress.js
While https://github.com/advplyr/audiobookshelf/pull/3546 fixes finishedAt for creating a progress updating a progress does not respect the changes.
Also should resolve #4094 if not already done by 3546
---
Current prod backup
=> fix updating progress not updating finishedAt

.github/workflows/close_blank_issues.yaml, .github/workflows/codeql.yml, .github/workflows/docker-build.yml, .github/workflows/i18n-integration.yml, .github/workflows/integration-test.yml, .github/workflows/lint-openapi.yml, .github/workflows/unit-tests.yml
- update action versions
- don't run docker action if not maintainer repo
=> ci: update actions

server/scanner/PodcastScanner.js
Re-scan podcasts wasn't waiting for promise to finish when removing episodes. This can result in an inaccurate `numEpisodes` column.
Removed episodes from scans will now remove the associated media progress and playlist media item.
No issue
=> Fix podcast re-scan promise

Dockerfile
In v2.22.0 the Dockerfile was improved to reduce the final image size (in #4150). 
The sqlite extension we use for unicode, [Nunicode](https://github.com/advplyr/audiobookshelf/pull/3468), was not being included in the final stage.
Since nunicode is an optional binary it didn't break anything, but the unicode unaccent and case-foldings provided by nunicode aren't being used.
Fixes #4297
Some container managers cache the env variables and since nunicode wasn't in the v2.22.0 Docker image, the cached env variable `NUSQLITE3_PATH` is a path that didn't exist.
The issues being reported about updating to v2.22.0 isn't technically a bug with Abs. 
Explained here https://github.com/advplyr/audiobookshelf/issues/4292#issuecomment-2887503644 (thanks @Vito0912)
The Docker image should include all …
=> Fix Dockerfile to include nunicode in the final stage

server/utils/queries/libraryItemsBookFilters.js
Use title as secondary sort when sorting books by author.
Fixes #4380
=> Update book library sort by author to use title as secondary sort #4380

client/components/controls/LibraryFilterSelect.vue, client/store/user.js, server/utils/queries/libraryItemsBookFilters.js, server/utils/queries/libraryItemsPodcastFilters.js
Add explicit filter for audiobooks.
Fixes https://github.com/advplyr/audiobookshelf/issues/2114. The inversion would still be handled by https://github.com/advplyr/audiobookshelf/issues/2833 if we decide to rename the issue.
Added books to the explicit list and applied a filter for it.
=> Add explicit filter

server/models/MediaProgress.js
In https://github.com/advplyr/audiobookshelf/pull/4326 I attempted to fix the issue where the `updatedAt` datetime was not being set using the timestamp in the request for media progress. That solution didn't work and instead the `updatedAt` remains unchanged on local media progress syncs.
This PR fixes that issue by running a separate raw query to set the `updatedAt` datetime. 
Fixes #4366 and possibly mobile app sync issues for downloaded media.
Sequelize v6 doesn't support manually setting the `updatedAt` timestamp. After trying all the suggested workarounds mentioned in issue threads on their repo I was only able to manually set it with a raw query.
This additional query only runs when the `lastUpdate` unix timestamp is included in requests to update media progress. That is used for …
=> Fix manually setting updatedAt of mediaProgresses using progress sync lastUpdate timestamp

server/controllers/SessionController.js
Redirects HLS transcode requests being made to the direct play endpoint (`/public/session/:id/track/:index`) instead of the HLS endpoint (`/hls/:stream/:file`).
Also return 500 when audioFile has no path
Fixes #4555
In android v0.10.0-beta a bug was introduced where transcodes are made to the direct play endpoint. This fixes that bug server side. It was fixed in the app here https://github.com/advplyr/audiobookshelf-app/pull/1636
Tested direct play in all clients and tested android transcodes redirect properly.
=> Fix server crash when transcode requests are made to the direct play endpoint 
